[workspace]
members = [
    "protocol",
    "protocol_io",
    "lib_utils",
    "device-cherry",
    "host-cherry",
    "device-embassy",
    "device-embassy-jtag",
]
exclude = [
    "plugin-nvs",
    "plugin_state_machine_std",
    "plugin-std",
    "host-std",
    "plugin-echo-example",
    "plugin-no-std",
    "plugin-host-std",
    "host-no-std",
    "plugin-std-nrf",
    "plugin-hostordevice-std",
    "plugin_config",
    "esp_nimble_plugin_config",
    "device-jtag",
    "host-jtag-no-std",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Babuabel Wanyeki <bwanyeki12@gmail.com>"]
repository = "https://github.com/Babu12345/ble-plugin"
edition = "2021"
rust-version = "1.77"

[profile.bench]
debug = true

[profile.release]
debug = false
opt-level = "s"
