[package]
name = "host-cherry"
version = "0.1.0"
edition = "2024"

[target.'cfg(all(target_arch = "xtensa", target_os = "espidf"))'.dependencies]
# Custom
protocol = { path = "../protocol", default-features = false, features = [
    "std",
] }
lib_utils = { path = "../lib_utils" }

# Crates
log = "0.4"
esp-idf-sys = { version = "0.36.1", default-features = false }
esp-idf-svc = { version = "0.51", default-features = false, features = ["alloc"] }
enumset = "1"
heapless = "0.8.0"

[[package.metadata.esp-idf-sys.extra_components]]
# remote_component = { name = "cherry-embedded/cherryusb", version = "1.5.2~2" }
component_dirs = "components/cherryusb"
bindings_header = "cherry_usb_host_bindings.h"
bindings_module = "cherry_host"


[features]
default = ["protocol_buffer"]
protocol_buffer = ["protocol/protocol_buffer"]
