[package]
name = "plugin-echo-example"
version = "0.1.0"
edition = "2021"

[dependencies]
## Files in shared directory
lib_utils = { path = "../lib_utils" }
protocol = { path = "../protocol", default-features = false, features = [
    "bincode_serialization",
    "protocol_buffer",
] }

## External crates
anyhow = { version = "1.0", default-features = false }
esp-backtrace = { version = "0.15.1", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-alloc = "0.7.0"

esp-hal = { version = "0.23.1", features = ["esp32s3"] }
esp-println = { version = "0.13.1", features = ["esp32s3", "log"] }

log = { version = "0.4.21" }
embassy-executor = { version = "0.7.0", features = ["task-arena-size-65536"] }

embassy-time = { version = "^0.4", features = ["generic-queue-8"] }
esp-hal-embassy = { version = "^0.6.0", features = ["esp32s3"] }
static_cell = { version = "2.1.0", features = ["nightly"] }
embassy-usb = "0.4.0"
embassy-futures = "0.1.1"
embassy-usb-logger = "0.4.0"
heapless = "0.8.0"
thiserror-no-std = "2.0.2"
embedded-hal-async = "1.0.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
