# GENERATED CODE - DO NOT EDIT MANUALLY
# This file is automatically generated from the Rust protocol library
# Source: test_fixtures/sample_protocol.rs
# Generator: codegen/src/bin/generate_python.rs

import attrs2bin
import attr
from enum import Enum
from typing import List, Optional

# ==================== CONSTANTS ====================

# Magic number for message validation
MESSAGE_MAGIC = 0xDEAD

# Maximum size for device names
MAX_NAME_SIZE = 64

# Default packet size for communication
DEFAULT_PACKET_SIZE = 256

# Derived constants
MESSAGE_MAGIC_BYTES = 2  # Size in bytes of the magic number field
MESSAGE_TYPE_ID_BYTES = 1  # Size in bytes of the message type identifier field  
DATA_BYTES_LENGTH_IN_BYTES = 2  # Size in bytes of the payload length field

# Message protocol constants
MESSAGE_HEADER_SIZE = MESSAGE_MAGIC_BYTES + MESSAGE_TYPE_ID_BYTES + DATA_BYTES_LENGTH_IN_BYTES  # 5 bytes

# ==================== ENUMS ====================

class MessageTypeId(Enum):
    """Message type identifiers for protocol dispatch"""
    # Configure BLE peripheral device
    HostCommandConfigurePeripheral = 0x01
    # Create a new BLE service
    HostCommandConfigureService = 0x02
    # Query service information
    HostCommandGetServiceInfo = 0x05
    # Data forwarded from BLE client
    PluginData = 0x80
    # Configuration error response
    PluginConfigurationError = 0x81
    # Service information response
    PluginServiceInfoResponse = 0x82

class BLEProperties(Enum):
    """BLE property flags for characteristics"""
    # Characteristic supports read operations
    Read = 0x02
    # Characteristic supports write operations
    Write = 0x08
    # Characteristic supports notifications
    Notify = 0x10
    # Characteristic supports indications
    Indicate = 0x20

# ==================== MESSAGE STRUCTURES ====================

@attr.s(auto_attribs=True)
class HostCommandConfigurePeripheral:
    """Configuration message for BLE peripheral"""
    name: str  # The device name to advertise
    uuid: str  # The primary service UUID
    max_connections: Optional[int]  # Maximum number of concurrent connections

@attr.s(auto_attribs=True)
class HostCommandConfigureService:
    """Service configuration message"""
    uuid: str  # Service UUID
    name: str  # Service name for identification
    is_primary: bool  # Whether this is a primary service
    characteristics: List[str]  # List of characteristic UUIDs

@attr.s(auto_attribs=True)
class HostCommandGetServiceInfo:
    """Service information query"""
    service_uuid: str  # Service UUID to query

@attr.s(auto_attribs=True)
class PluginData:
    """Data message from plugin to host"""
    connection_id: int  # Connection handle
    characteristic_uuid: str  # Characteristic UUID that received data
    data: List[attrs2bin.U8]  # The actual data payload
    timestamp: int  # Timestamp when data was received

@attr.s(auto_attribs=True)
class PluginConfigurationError:
    """Configuration error response"""
    error_code: int  # Error code
    message: str  # Human-readable error message
    context: Optional[str]  # Optional context about what was being configured

@attr.s(auto_attribs=True)
class CharacteristicInfo:
    """Information about a BLE characteristic"""
    uuid: str  # Characteristic UUID
    properties: BLEProperties  # Characteristic properties
    current_value: Optional[List[attrs2bin.U8]]  # Current value if readable
    notifications_enabled: bool  # Whether notifications are enabled

@attr.s(auto_attribs=True)
class PluginServiceInfoResponse:
    """Response to service information query"""
    service_uuid: str  # Service UUID
    service_name: str  # Service name
    characteristics: List[CharacteristicInfo]  # List of characteristic information
    is_active: bool  # Whether service is currently active

# ==================== MESSAGE TYPE MAPPING ====================

# Map message types to their type IDs
MESSAGE_TYPE_MAP = {
    HostCommandConfigurePeripheral: MessageTypeId.HostCommandConfigurePeripheral,
    HostCommandConfigureService: MessageTypeId.HostCommandConfigureService,
    HostCommandGetServiceInfo: MessageTypeId.HostCommandGetServiceInfo,
    PluginData: MessageTypeId.PluginData,
    PluginConfigurationError: MessageTypeId.PluginConfigurationError,
    PluginServiceInfoResponse: MessageTypeId.PluginServiceInfoResponse,
}

# Reverse map for easy lookup
TYPE_ID_TO_MESSAGE_TYPE = {v: k for k, v in MESSAGE_TYPE_MAP.items()}