[package]
name = "protocol"
version = "0.1.0"
edition = "2021"


[dependencies]
# Custom
lib_utils = { path = "../lib_utils" }
protocol_io = { path = "../protocol_io" }
# Crates
serde = { version = "^1.0.217", default-features = false, features = [
    "derive",
    "alloc",
] }
bincode = { version = "2.0.1", default-features = false, features = [
    "serde",
], optional = true }
log = "0.4"
embassy-sync = { version = "0.6.1", default-features = false }
strum = { version = "0.27.2", default-features = false, features = ["derive"] }
# prost = { version = "0.14.1", default-features = false, features = ["derive"] }
prost = { git = "https://github.com/Babu12345/prost", default-features = false, features = [
    "derive",
] }
quick-protobuf = { version = "0.8", default-features = false, optional = true }
heapless = { version = "0.8.0" }

[build-dependencies]
prost-build = "0.14.1"
pb-rs = "0.10.0"

[lib]
doctest = false

[features]
default = ["std", "protocol_buffer"]
std = ["serde/std", "bincode/alloc", "prost/std", "quick-protobuf/std"]
bincode_serialization = ["bincode"]
protocol_buffer = []
quick_protocol_buffer = ["quick-protobuf"]
