"""
Python equivalents of the Rust test structures used for regression testing.

These structures mirror the independent test structures defined in the Rust
generate_test_data.rs file, allowing us to deserialize and validate the
binary data generated by the Rust protocol implementation.
"""

import attr
from enum import Enum
from typing import List
import attrs2bin

# Type aliases for cleaner code - use basic types compatible with attrs2bin
U8 = attrs2bin.U8
U16 = attrs2bin.U16
U32 = attrs2bin.U32
I8 = attrs2bin.I8
I16 = attrs2bin.I16
I32 = attrs2bin.I32
U64 = attrs2bin.UnsignedInt  # unsigned int corresponds to U64
I64 = attrs2bin.SignedInt    # signed int corresponds to I64


# ====== TEST ENUMS ======

class BLEPropertiesTest(Enum):
    """Test enum for BLE properties - mirrors Rust BLEPropertiesTest"""
    TestRead: U8 = 10
    TestWrite: U8 = 11
    TestNotify: U8 = 12
    TestIndicate: U8 = 13


class BluetoothAddressTypeTest(Enum):
    """Test enum for bluetooth address types - mirrors Rust BluetoothAddressTypeTest"""
    TestPublic: U8 = 20
    TestRandom: U8 = 21
    TestResolvable: U8 = 22


class DataSendTypeTest(Enum):
    """Test enum for data send types - mirrors Rust DataSendTypeTest"""
    TestNotification: U8 = 30
    TestRead: U8 = 31
    TestWrite: U8 = 32


class ConfigurationErrorTest(Enum):
    """Test enum for configuration errors - mirrors Rust ConfigurationErrorTest"""
    TestNameTooLong: U8 = 40
    TestInvalidUuid: U8 = 41
    TestServiceMissing: U8 = 42
    TestCharacteristicMissing: U8 = 43


# ====== TEST HOST COMMAND STRUCTURES ======

@attr.s(auto_attribs=True)
class HostCommandConfigurePeripheralTest:
    """Test host command for peripheral configuration - mirrors Rust struct"""
    test_name: str  # HeaplessString<20> in Rust
    test_uuid: bytes  # Uuid in Rust (16 bytes)
    test_enabled: bool
    test_power_level: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class HostCommandConfigureServiceTest:
    """Test host command for service configuration - mirrors Rust struct"""
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_priority: U8  # u8 in Rust - use U8 for compatibility
    test_visible: bool


@attr.s(auto_attribs=True)
class HostCommandConfigureCharacteristicTest:
    """Test host command for characteristic configuration - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_properties: List[BLEPropertiesTest]  # HeaplessVec<BLEPropertiesTest, 3> in Rust
    test_security_level: U8  # u8 in Rust - keep U8


@attr.s(auto_attribs=True)
class HostCommandConfigureCharacteristicReadTest:
    """Test host command for characteristic read configuration - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_default_value: List[U8]  # HeaplessVec<u8, 16> in Rust
    test_read_permissions: U8  # u8 in Rust - keep U8


@attr.s(auto_attribs=True)
class HostCommandGetServiceInfoTest:
    """Test host command for service info query - mirrors Rust struct"""
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_include_characteristics: bool


@attr.s(auto_attribs=True)
class HostCommandGetCharacteristicInfoTest:
    """Test host command for characteristic info query - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_detailed_info: bool


@attr.s(auto_attribs=True)
class HostCommandStartAdvertisementTest:
    """Test host command for advertisement start - mirrors Rust struct"""
    test_allow_multi_connect: bool
    test_advertisement_interval: U8  # u8 in Rust - use U8 for compatibility
    test_tx_power: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class HostCommandNotifyCharacteristicValueTest:
    """Test host command for characteristic value notification - mirrors Rust struct"""
    test_device_address: List[U8]  # [u8; 6] in Rust
    test_address_type: BluetoothAddressTypeTest
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_notification_value: List[U8]  # HeaplessVec<u8, 20> in Rust
    test_confirm_required: bool


# ====== TEST PLUGIN RESPONSE STRUCTURES ======

@attr.s(auto_attribs=True)
class PluginDataTest:
    """Test plugin response for data forwarding - mirrors Rust struct"""
    test_source_id: bytes  # Uuid in Rust (16 bytes)
    test_send_type: DataSendTypeTest
    test_payload: bytes  # &[u8] in Rust
    test_timestamp: U8  # u8 in Rust - use U8 for compatibility
    test_connection_handle: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class PluginConfigurationErrorTest:
    """Test plugin configuration error response - mirrors Rust struct"""
    test_error_type: ConfigurationErrorTest
    test_error_code: U8  # u8 in Rust - use U8 for compatibility
    test_error_description: str  # HeaplessString<32> in Rust


@attr.s(auto_attribs=True)
class PluginServiceInfoResponseTest:
    """Test plugin service info response - mirrors Rust struct"""
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_characteristic_uuids: List[bytes]  # HeaplessVec<Uuid, 8> in Rust
    test_service_exists: bool
    test_service_active: bool
    test_characteristic_count: U8  # u8 in Rust - keep U8


@attr.s(auto_attribs=True)
class PluginCharacteristicInfoResponseTest:
    """Test plugin characteristic info response - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_properties: List[BLEPropertiesTest]  # HeaplessVec<BLEPropertiesTest, 3> in Rust
    test_char_exists: bool
    test_value_length: U8  # u8 in Rust - use U8 for compatibility
    test_client_config: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class PluginAuthenticationCompletedResponseTest:
    """Test plugin authentication completed response - mirrors Rust struct"""
    test_device_address: List[U8]  # [u8; 6] in Rust
    test_address_type: BluetoothAddressTypeTest
    test_auth_success: bool
    test_auth_level: U8  # u8 in Rust - keep U8
    test_bond_created: bool


# ====== INTEGER TYPE REGRESSION TEST STRUCTURES ======

@attr.s(auto_attribs=True)
class IntegerTypesTestSmall:
    """Small test struct with all integer types - fits in 64 bytes"""
    test_u8: U8
    test_u16: U16
    test_u32: U32
    test_i8: I8
    test_i16: I16
    test_i32: I32
    # Total so far: 1 + 2 + 4 + 1 + 2 + 4 = 14 bytes


@attr.s(auto_attribs=True)
class IntegerTypesTestWithU64I64:
    """Test struct with U64/I64 types - designed to fit in 64 bytes"""
    test_u64: U64
    test_i64: I64
    test_u16: U16
    test_i16: I16
    test_enabled: bool
    # Total: 8 + 8 + 2 + 2 + 1 = 21 bytes


@attr.s(auto_attribs=True)
class IntegerTypesTestMixed:
    """Mixed integer types test - compact for 64 bytes"""
    test_u8: U8
    test_i8: I8
    test_u16: U16
    test_i16: I16
    test_bool: bool
    # Total: 1 + 1 + 2 + 2 + 1 = 7 bytes


# ====== UTILITY FUNCTIONS ======

def uuid_bytes_to_str(uuid_bytes: bytes) -> str:
    """Convert UUID bytes to string representation."""
    import uuid as uuid_module
    if len(uuid_bytes) != 16:
        raise ValueError(f"UUID bytes must be 16 bytes, got {len(uuid_bytes)}")
    return str(uuid_module.UUID(bytes=uuid_bytes))


def validate_test_enum_values():
    """Validate that test enum values match expected values from Rust."""
    # BLEPropertiesTest
    assert BLEPropertiesTest.TestRead.value == 10
    assert BLEPropertiesTest.TestWrite.value == 11
    assert BLEPropertiesTest.TestNotify.value == 12
    assert BLEPropertiesTest.TestIndicate.value == 13
    
    # BluetoothAddressTypeTest
    assert BluetoothAddressTypeTest.TestPublic.value == 20
    assert BluetoothAddressTypeTest.TestRandom.value == 21
    assert BluetoothAddressTypeTest.TestResolvable.value == 22
    
    # DataSendTypeTest
    assert DataSendTypeTest.TestNotification.value == 30
    assert DataSendTypeTest.TestRead.value == 31
    assert DataSendTypeTest.TestWrite.value == 32
    
    # ConfigurationErrorTest
    assert ConfigurationErrorTest.TestNameTooLong.value == 40
    assert ConfigurationErrorTest.TestInvalidUuid.value == 41
    assert ConfigurationErrorTest.TestServiceMissing.value == 42
    assert ConfigurationErrorTest.TestCharacteristicMissing.value == 43


if __name__ == "__main__":
    # Validate enum values when run directly
    validate_test_enum_values()
    print("✓ All test enum values validated successfully!")