"""
Python equivalents of the Rust test structures used for regression testing.

These structures mirror the independent test structures defined in the Rust
generate_test_data.rs file, allowing us to deserialize and validate the
binary data generated by the Rust protocol implementation.
"""

import attr
from enum import Enum
from typing import List
import attrs2bin

# Type aliases for cleaner code - use basic types compatible with attrs2bin
U8 = attrs2bin.U8


# ====== TEST ENUMS ======

class TestBLEProperties(Enum):
    """Test enum for BLE properties - mirrors Rust TestBLEProperties"""
    TestRead: U8 = 10
    TestWrite: U8 = 11
    TestNotify: U8 = 12
    TestIndicate: U8 = 13


class TestBluetoothAddressType(Enum):
    """Test enum for bluetooth address types - mirrors Rust TestBluetoothAddressType"""
    TestPublic: U8 = 20
    TestRandom: U8 = 21
    TestResolvable: U8 = 22


class TestDataSendType(Enum):
    """Test enum for data send types - mirrors Rust TestDataSendType"""
    TestNotification: U8 = 30
    TestRead: U8 = 31
    TestWrite: U8 = 32


class TestConfigurationError(Enum):
    """Test enum for configuration errors - mirrors Rust TestConfigurationError"""
    TestNameTooLong: U8 = 40
    TestInvalidUuid: U8 = 41
    TestServiceMissing: U8 = 42
    TestCharacteristicMissing: U8 = 43


# ====== TEST HOST COMMAND STRUCTURES ======

@attr.s(auto_attribs=True)
class TestHostCommandConfigurePeripheral:
    """Test host command for peripheral configuration - mirrors Rust struct"""
    test_name: str  # HeaplessString<20> in Rust
    test_uuid: bytes  # Uuid in Rust (16 bytes)
    test_enabled: bool
    test_power_level: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class TestHostCommandConfigureService:
    """Test host command for service configuration - mirrors Rust struct"""
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_priority: U8  # u8 in Rust - use U8 for compatibility
    test_visible: bool


@attr.s(auto_attribs=True)
class TestHostCommandConfigureCharacteristic:
    """Test host command for characteristic configuration - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_properties: List[TestBLEProperties]  # HeaplessVec<TestBLEProperties, 3> in Rust
    test_security_level: U8  # u8 in Rust - keep U8


@attr.s(auto_attribs=True)
class TestHostCommandConfigureCharacteristicRead:
    """Test host command for characteristic read configuration - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_default_value: List[U8]  # HeaplessVec<u8, 16> in Rust
    test_read_permissions: U8  # u8 in Rust - keep U8


@attr.s(auto_attribs=True)
class TestHostCommandGetServiceInfo:
    """Test host command for service info query - mirrors Rust struct"""
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_include_characteristics: bool


@attr.s(auto_attribs=True)
class TestHostCommandGetCharacteristicInfo:
    """Test host command for characteristic info query - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_detailed_info: bool


@attr.s(auto_attribs=True)
class TestHostCommandStartAdvertisement:
    """Test host command for advertisement start - mirrors Rust struct"""
    test_allow_multi_connect: bool
    test_advertisement_interval: U8  # u8 in Rust - use U8 for compatibility
    test_tx_power: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class TestHostCommandNotifyCharacteristicValue:
    """Test host command for characteristic value notification - mirrors Rust struct"""
    test_device_address: List[U8]  # [u8; 6] in Rust
    test_address_type: TestBluetoothAddressType
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_notification_value: List[U8]  # HeaplessVec<u8, 20> in Rust
    test_confirm_required: bool


# ====== TEST PLUGIN RESPONSE STRUCTURES ======

@attr.s(auto_attribs=True)
class TestPluginData:
    """Test plugin response for data forwarding - mirrors Rust struct"""
    test_source_id: bytes  # Uuid in Rust (16 bytes)
    test_send_type: TestDataSendType
    test_payload: bytes  # &[u8] in Rust
    test_timestamp: U8  # u8 in Rust - use U8 for compatibility
    test_connection_handle: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class TestPluginConfigurationError:
    """Test plugin configuration error response - mirrors Rust struct"""
    test_error_type: TestConfigurationError
    test_error_code: U8  # u8 in Rust - use U8 for compatibility
    test_error_description: str  # HeaplessString<32> in Rust


@attr.s(auto_attribs=True)
class TestPluginServiceInfoResponse:
    """Test plugin service info response - mirrors Rust struct"""
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_characteristic_uuids: List[bytes]  # HeaplessVec<Uuid, 8> in Rust
    test_service_exists: bool
    test_service_active: bool
    test_characteristic_count: U8  # u8 in Rust - keep U8


@attr.s(auto_attribs=True)
class TestPluginCharacteristicInfoResponse:
    """Test plugin characteristic info response - mirrors Rust struct"""
    test_char_uuid: bytes  # Uuid in Rust (16 bytes)
    test_service_uuid: bytes  # Uuid in Rust (16 bytes)
    test_properties: List[TestBLEProperties]  # HeaplessVec<TestBLEProperties, 3> in Rust
    test_char_exists: bool
    test_value_length: U8  # u8 in Rust - use U8 for compatibility
    test_client_config: U8  # u8 in Rust - use U8 for compatibility


@attr.s(auto_attribs=True)
class TestPluginAuthenticationCompletedResponse:
    """Test plugin authentication completed response - mirrors Rust struct"""
    test_device_address: List[U8]  # [u8; 6] in Rust
    test_address_type: TestBluetoothAddressType
    test_auth_success: bool
    test_auth_level: U8  # u8 in Rust - keep U8
    test_bond_created: bool


# ====== UTILITY FUNCTIONS ======

def uuid_bytes_to_str(uuid_bytes: bytes) -> str:
    """Convert UUID bytes to string representation."""
    import uuid as uuid_module
    if len(uuid_bytes) != 16:
        raise ValueError(f"UUID bytes must be 16 bytes, got {len(uuid_bytes)}")
    return str(uuid_module.UUID(bytes=uuid_bytes))


def validate_test_enum_values():
    """Validate that test enum values match expected values from Rust."""
    # TestBLEProperties
    assert TestBLEProperties.TestRead.value == 10
    assert TestBLEProperties.TestWrite.value == 11
    assert TestBLEProperties.TestNotify.value == 12
    assert TestBLEProperties.TestIndicate.value == 13
    
    # TestBluetoothAddressType
    assert TestBluetoothAddressType.TestPublic.value == 20
    assert TestBluetoothAddressType.TestRandom.value == 21
    assert TestBluetoothAddressType.TestResolvable.value == 22
    
    # TestDataSendType
    assert TestDataSendType.TestNotification.value == 30
    assert TestDataSendType.TestRead.value == 31
    assert TestDataSendType.TestWrite.value == 32
    
    # TestConfigurationError
    assert TestConfigurationError.TestNameTooLong.value == 40
    assert TestConfigurationError.TestInvalidUuid.value == 41
    assert TestConfigurationError.TestServiceMissing.value == 42
    assert TestConfigurationError.TestCharacteristicMissing.value == 43


if __name__ == "__main__":
    # Validate enum values when run directly
    validate_test_enum_values()
    print("✓ All test enum values validated successfully!")