"""
Streamlined protocol regression tests using binary test data generated from Rust protocol library.

This module tests the serialization/deserialization compatibility between the Rust
protocol implementation and the Python plugin_host library by using pre-generated
binary test data.

The test data is generated by the Rust binary `generate_test_data` which creates
independent test structures, enums, and constants that don't interfere with the
main codebase, ensuring we can test changes independently.
"""

import struct
from pathlib import Path
from typing import Dict, Any

import pytest
import attrs2bin

# Import test structures for deserialization validation
from test_structures import (
    # Test enums
    BLEPropertiesTest,
    DataSendTypeTest,
    
    # Test host command structures
    HostCommandConfigurePeripheralTest,
    HostCommandConfigureServiceTest,
    HostCommandConfigureCharacteristicTest,
    
    # Test plugin response structures
    PluginDataTest,
    PluginServiceInfoResponseTest,
    
    # Integer type test structures
    IntegerTypesTestSmall,
    IntegerTypesTestWithU64I64,
    IntegerTypesTestMixed,
    
    # Utility functions
    validate_test_enum_values,
)

from plugin_host.generated_types import (
    # Constants
    MESSAGE_MAGIC,
    MESSAGE_HEADER_SIZE,
    DEFAULT_PACKET_SIZE,
    
    # Message type mapping
    MessageTypeId,
)


def get_test_data_dir() -> Path:
    """Get the path to the binary test data directory."""
    current_dir = Path(__file__).parent
    return current_dir.parent / "python_regression_test_data" / "binary"


def load_binary_test_file(filename: str) -> bytes:
    """Load a binary test file and return its contents."""
    test_data_dir = get_test_data_dir()
    file_path = test_data_dir / filename
    
    if not file_path.exists():
        pytest.skip(f"Test data file not found: {file_path}")
    
    with open(file_path, 'rb') as f:
        return f.read()


def parse_protocol_header(data: bytes) -> Dict[str, Any]:
    """Parse the protocol header from binary data."""
    if len(data) < MESSAGE_HEADER_SIZE:
        raise ValueError(f"Data too short for header: {len(data)} < {MESSAGE_HEADER_SIZE}")
    
    # Parse header: magic (2 bytes) + type_id (1 byte) + length (2 bytes)
    magic = struct.unpack('<H', data[0:2])[0]  # little-endian uint16
    type_id = data[2]
    length = struct.unpack('<H', data[3:5])[0]  # little-endian uint16
    
    return {
        'magic': magic,
        'type_id': type_id,
        'length': length,
        'payload': data[MESSAGE_HEADER_SIZE:MESSAGE_HEADER_SIZE + length]
    }


def verify_protocol_header(header: Dict[str, Any], expected_type_id: MessageTypeId):
    """Verify that a protocol header is valid."""
    assert header['magic'] == MESSAGE_MAGIC, f"Invalid magic number: 0x{header['magic']:04x}"
    assert header['type_id'] == expected_type_id.value, f"Wrong type ID: {header['type_id']} != {expected_type_id.value}"
    assert header['length'] > 0, "Payload length should be greater than 0"
    assert header['length'] <= DEFAULT_PACKET_SIZE - MESSAGE_HEADER_SIZE, "Payload too large"


def create_python_test_data_and_deserialize(test_struct_class, **kwargs):
    """Create test data in Python format, serialize it, then deserialize it for validation."""
    # Create test instance
    test_instance = test_struct_class(**kwargs)
    
    # Serialize using attrs2bin
    serialized = attrs2bin.serialize(test_instance)
    
    # Deserialize using attrs2bin
    deserialized = attrs2bin.deserialize(serialized, test_struct_class)
    
    # Validate round-trip worked
    assert test_instance == deserialized, f"Round-trip failed for {test_struct_class.__name__}"
    
    return deserialized, serialized


class TestCrossLanguageCompatibility:
    """Test cross-language serialization/deserialization compatibility between Rust and Python."""
    
    def test_rust_to_python_deserialization(self):
        """Test deserialization of Rust-generated binary data into Python structures."""
        # Test HostCommandConfigurePeripheralTest from Rust binary data
        binary_data = load_binary_test_file("test_host_configure_peripheral.bin")
        header = parse_protocol_header(binary_data)
        
        # Verify header first
        verify_protocol_header(header, MessageTypeId.HostCommandConfigurePeripheral)
        
        # Deserialize payload using Python test structure
        result = attrs2bin.deserialize(header['payload'], HostCommandConfigurePeripheralTest)
        
        # Validate deserialized data matches expected Rust values
        assert result.test_name == "TestPeripheral", f"Expected 'TestPeripheral', got '{result.test_name}'"
        assert len(result.test_uuid) == 16, "UUID should be 16 bytes"
        assert result.test_enabled is True, "test_enabled should be True"
        power_level = result.test_power_level.value if hasattr(result.test_power_level, 'value') else result.test_power_level
        assert power_level == 4, f"Expected power_level=4, got {power_level}"
        
        print(f"✅ Cross-language deserialization successful: {result.test_name}, "
              f"uuid={result.test_uuid.hex()[:8]}..., enabled={result.test_enabled}, power={power_level}")
    
    def test_multiple_message_types_deserialization(self):
        """Test that multiple message types can be deserialized correctly."""
        test_cases = [
            ("test_host_configure_peripheral.bin", MessageTypeId.HostCommandConfigurePeripheral, HostCommandConfigurePeripheralTest),
            ("test_host_configure_service.bin", MessageTypeId.HostCommandConfigureService, HostCommandConfigureServiceTest),
            ("test_plugin_data.bin", MessageTypeId.PluginData, PluginDataTest),
            ("test_plugin_service_info_response.bin", MessageTypeId.PluginServiceInfoResponse, PluginServiceInfoResponseTest),
        ]
        
        for filename, expected_type_id, struct_class in test_cases:
            binary_data = load_binary_test_file(filename)
            header = parse_protocol_header(binary_data)
            
            # Verify header
            verify_protocol_header(header, expected_type_id)
            
            # Test that deserialization doesn't crash
            try:
                attrs2bin.deserialize(header['payload'], struct_class)
                print(f"✅ {filename}: Deserialized {struct_class.__name__}")
            except Exception as e:
                pytest.fail(f"Failed to deserialize {filename} as {struct_class.__name__}: {e}")
    
    def test_round_trip_compatibility(self):
        """Test that Python can read Rust data and produce equivalent structures."""
        import uuid as uuid_module
        
        # Create the same data in Python that Rust creates
        expected_name = "TestPeripheral"
        expected_uuid = uuid_module.UUID("12345678-1234-5678-9abc-123456789abc")
        expected_enabled = True
        expected_power = 4
        
        # Load Rust-generated data
        binary_data = load_binary_test_file("test_host_configure_peripheral.bin")
        header = parse_protocol_header(binary_data)
        rust_result = attrs2bin.deserialize(header['payload'], HostCommandConfigurePeripheralTest)
        
        # Create equivalent Python data
        python_result, _ = create_python_test_data_and_deserialize(
            HostCommandConfigurePeripheralTest,
            test_name=expected_name,
            test_uuid=expected_uuid.bytes,
            test_enabled=expected_enabled,
            test_power_level=attrs2bin.U8(expected_power)
        )
        
        # Compare logical equivalence (values should match)
        assert rust_result.test_name == python_result.test_name
        assert rust_result.test_uuid == python_result.test_uuid
        assert rust_result.test_enabled == python_result.test_enabled
        
        rust_power = rust_result.test_power_level.value if hasattr(rust_result.test_power_level, 'value') else rust_result.test_power_level
        python_power = python_result.test_power_level.value if hasattr(python_result.test_power_level, 'value') else python_result.test_power_level
        assert rust_power == python_power
        
        print(f"✅ Cross-language compatibility verified: Rust and Python produce equivalent data structures")


class TestPythonStructures:
    """Test Python test structures independently."""
    
    def test_enum_values_consistency(self):
        """Test that test enum values match the expected Rust implementation."""
        validate_test_enum_values()
        print("✅ All test enum values validated against expected Rust values")
    
    def test_python_serialization_round_trip(self):
        """Test round-trip serialization for Python test structures (attrs2bin only)."""
        import uuid as uuid_module
        
        # Test multiple structures
        test_cases = [
            (HostCommandConfigureServiceTest, {
                'test_service_uuid': uuid_module.uuid4().bytes,
                'test_priority': attrs2bin.U8(100),
                'test_visible': True
            }),
            (HostCommandConfigureCharacteristicTest, {
                'test_char_uuid': uuid_module.uuid4().bytes,
                'test_service_uuid': uuid_module.uuid4().bytes,
                'test_properties': [BLEPropertiesTest.TestRead, BLEPropertiesTest.TestWrite],
                'test_security_level': attrs2bin.U8(2)
            }),
        ]
        
        for struct_class, kwargs in test_cases:
            original = struct_class(**kwargs)
            serialized = attrs2bin.serialize(original)
            deserialized = attrs2bin.deserialize(serialized, struct_class)
            
            # Validate round-trip
            assert original == deserialized, f"Round-trip failed for {struct_class.__name__}"
            
        print("✅ Python round-trip serialization successful for all test structures")
    
    def test_enum_serialization_consistency(self):
        """Test that enum serialization works correctly within Python."""
        # Test BLEPropertiesTest enum
        for prop in BLEPropertiesTest:
            serialized = attrs2bin.serialize(prop)
            deserialized = attrs2bin.deserialize(serialized, BLEPropertiesTest)
            assert prop == deserialized, f"Enum round-trip failed for {prop}"
        
        # Test DataSendTypeTest enum
        for send_type in DataSendTypeTest:
            serialized = attrs2bin.serialize(send_type)
            deserialized = attrs2bin.deserialize(serialized, DataSendTypeTest)
            assert send_type == deserialized, f"Enum round-trip failed for {send_type}"
        
        print("✅ All test enums pass Python round-trip serialization")
    
    def test_integer_types_round_trip(self):
        """Test round-trip serialization for all integer types."""
        # Test IntegerTypesTestSmall
        small_test = IntegerTypesTestSmall(
            test_u8=attrs2bin.U8(255),
            test_u16=attrs2bin.U16(65535),
            test_u32=attrs2bin.U32(4294967295),
            test_i8=attrs2bin.I8(-128),
            test_i16=attrs2bin.I16(-32768),
            test_i32=attrs2bin.I32(-2147483648),
            test_f32=attrs2bin.Float32(3.14159),
            test_f64=attrs2bin.Float64(2.718281828459045),
        )
        serialized = attrs2bin.serialize(small_test)
        deserialized = attrs2bin.deserialize(serialized, IntegerTypesTestSmall)
        
        # Check integer fields for exact equality
        assert small_test.test_u8 == deserialized.test_u8
        assert small_test.test_u16 == deserialized.test_u16  
        assert small_test.test_u32 == deserialized.test_u32
        assert small_test.test_i8 == deserialized.test_i8
        assert small_test.test_i16 == deserialized.test_i16
        assert small_test.test_i32 == deserialized.test_i32
        
        # Check floating-point fields with approximate equality
        assert abs(small_test.test_f32 - deserialized.test_f32) < 1e-5
        assert abs(small_test.test_f64 - deserialized.test_f64) < 1e-14
        
        # Test IntegerTypesTestWithU64I64
        u64_i64_test = IntegerTypesTestWithU64I64(
            test_u64=attrs2bin.UnsignedInt(18446744073709551615),  # Max U64
            test_i64=attrs2bin.SignedInt(-9223372036854775808),    # Min I64
            test_u16=attrs2bin.U16(12345),
            test_i16=attrs2bin.I16(-12345),
            test_enabled=True,
        )
        serialized = attrs2bin.serialize(u64_i64_test)
        deserialized = attrs2bin.deserialize(serialized, IntegerTypesTestWithU64I64)
        assert u64_i64_test == deserialized, "Integer types U64/I64 round-trip failed"
        
        # Test IntegerTypesTestMixed
        mixed_test = IntegerTypesTestMixed(
            test_u8=attrs2bin.U8(42),
            test_i8=attrs2bin.I8(-42),
            test_u16=attrs2bin.U16(1234),
            test_i16=attrs2bin.I16(-1234),
            test_f32=attrs2bin.Float32(1.414213562373095),  # sqrt(2)
            test_bool=True,
        )
        serialized = attrs2bin.serialize(mixed_test)
        deserialized = attrs2bin.deserialize(serialized, IntegerTypesTestMixed)
        
        # Check integer and bool fields for exact equality
        assert mixed_test.test_u8 == deserialized.test_u8
        assert mixed_test.test_i8 == deserialized.test_i8
        assert mixed_test.test_u16 == deserialized.test_u16
        assert mixed_test.test_i16 == deserialized.test_i16
        assert mixed_test.test_bool == deserialized.test_bool
        
        # Check floating-point field with approximate equality
        assert abs(mixed_test.test_f32 - deserialized.test_f32) < 1e-5
        
        print("✅ All integer types pass Python round-trip serialization")
    
    def test_integer_types_cross_language_compatibility(self):
        """Test that Python can deserialize Rust-generated integer type data."""
        # Test IntegerTypesTestSmall
        try:
            small_data = load_binary_test_file("test_integer_types_small.bin")
            header = parse_protocol_header(small_data)
            small_result = attrs2bin.deserialize(header['payload'], IntegerTypesTestSmall)
            
            # Validate values match what Rust generates
            assert small_result.test_u8 == 255
            assert small_result.test_u16 == 65535
            assert small_result.test_u32 == 4294967295
            assert small_result.test_i8 == -128
            assert small_result.test_i16 == -32768
            assert small_result.test_i32 == -2147483648
            assert abs(small_result.test_f32 - 3.14159) < 1e-5  # f32 precision
            assert abs(small_result.test_f64 - 2.718281828459045) < 1e-14  # f64 precision
            
            print("✅ IntegerTypesTestSmall cross-language compatibility verified")
        except FileNotFoundError:
            pytest.skip("Integer types small test data not generated yet")
        
        # Test IntegerTypesTestWithU64I64
        try:
            u64_i64_data = load_binary_test_file("test_integer_types_u64_i64.bin")
            header = parse_protocol_header(u64_i64_data)
            u64_i64_result = attrs2bin.deserialize(header['payload'], IntegerTypesTestWithU64I64)
            
            # Validate values match what Rust generates
            assert u64_i64_result.test_u64 == 18446744073709551615  # Max U64
            assert u64_i64_result.test_i64 == -9223372036854775808   # Min I64
            assert u64_i64_result.test_u16 == 12345
            assert u64_i64_result.test_i16 == -12345
            assert u64_i64_result.test_enabled is True
            
            print("✅ IntegerTypesTestWithU64I64 cross-language compatibility verified")
        except FileNotFoundError:
            pytest.skip("Integer types U64/I64 test data not generated yet")
        
        # Test IntegerTypesTestMixed
        try:
            mixed_data = load_binary_test_file("test_integer_types_mixed.bin")
            header = parse_protocol_header(mixed_data)
            mixed_result = attrs2bin.deserialize(header['payload'], IntegerTypesTestMixed)
            
            # Validate values match what Rust generates
            assert mixed_result.test_u8 == 42
            assert mixed_result.test_i8 == -42
            assert mixed_result.test_u16 == 1234
            assert mixed_result.test_i16 == -1234
            assert abs(mixed_result.test_f32 - 1.414213562373095) < 1e-5  # f32 precision
            assert mixed_result.test_bool is True
            
            print("✅ IntegerTypesTestMixed cross-language compatibility verified")
        except FileNotFoundError:
            pytest.skip("Integer types mixed test data not generated yet")
        
        print("✅ All integer types cross-language compatibility verified")


class TestBinaryDataIntegrity:
    """Test the integrity and structure of generated binary data."""
    
    def test_binary_data_integrity(self):
        """Test that all binary files exist, have correct sizes, and valid headers."""
        expected_files = [
            "test_host_configure_peripheral.bin",
            "test_host_configure_service.bin", 
            "test_host_configure_characteristic.bin",
            "test_plugin_data.bin",
            "test_plugin_service_info_response.bin",
        ]
        
        test_data_dir = get_test_data_dir()
        
        for filename in expected_files:
            file_path = test_data_dir / filename
            
            # Check file exists
            assert file_path.exists(), f"Missing test data file: {filename}"
            
            # Check file size
            file_size = file_path.stat().st_size
            assert file_size == DEFAULT_PACKET_SIZE, f"File {filename} has wrong size: {file_size} != {DEFAULT_PACKET_SIZE}"
            
            # Check header magic number
            with open(file_path, 'rb') as f:
                data = f.read()
            
            header = parse_protocol_header(data)
            assert header['magic'] == MESSAGE_MAGIC, f"File {filename} has wrong magic: 0x{header['magic']:04x}"
            
        print(f"✅ All {len(expected_files)} binary files pass integrity checks")


def test_compatibility_status():
    """Document the current cross-language serialization compatibility status."""
    print("\n" + "="*60)
    print("CROSS-LANGUAGE SERIALIZATION COMPATIBILITY")
    print("="*60)
    print("Status: Rust bincode and Python attrs2bin are now COMPATIBLE!")
    print("This test suite validates:")
    print("1. ✅ Protocol headers (magic, type_id, length) - COMPATIBLE")
    print("2. ✅ Message structure validation - COMPATIBLE") 
    print("3. ✅ Python attrs2bin round-trip - WORKS")
    print("4. ✅ Rust bincode round-trip - WORKS (tested in Rust)")
    print("5. ✅ Cross-language payload deserialization - COMPATIBLE!")
    print("\nCompatibility achieved by:")
    print("- Using only U8 types for numeric values (avoiding u16, i8, u64)")
    print("- Consistent string and UUID handling")
    print("- Matching enum value assignments")
    print("- Identical struct field ordering")
    print("\nFull interoperability is now possible between Rust and Python!")
    print("="*60)


def test_regression_suite_info():
    """Print information about the regression test suite."""
    test_data_dir = get_test_data_dir()
    
    print("\n" + "="*60)
    print("STREAMLINED PROTOCOL REGRESSION TEST SUITE")
    print("="*60)
    print(f"Test data directory: {test_data_dir}")
    print(f"Generated binary files: {len(list(test_data_dir.glob('*.bin')))}")
    print(f"Protocol magic number: 0x{MESSAGE_MAGIC:04x}")
    print(f"Header size: {MESSAGE_HEADER_SIZE} bytes")
    print(f"Packet size: {DEFAULT_PACKET_SIZE} bytes")
    
    print("\nTest coverage:")
    print("  ✅ Cross-language deserialization (Rust → Python)")
    print("  ✅ Python structure round-trip serialization")  
    print("  ✅ Binary data integrity validation")
    print("  ✅ Protocol header validation")
    print("  ✅ Enum consistency verification")
    print("="*60)