"""
Streamlined protocol regression tests using binary test data generated from Rust protocol library.

This module tests the serialization/deserialization compatibility between the Rust
protocol implementation and the Python plugin_host library by using pre-generated
binary test data.

The test data is generated by the Rust binary `generate_test_data` which creates
independent test structures, enums, and constants that don't interfere with the
main codebase, ensuring we can test changes independently.
"""

import struct
from pathlib import Path
from typing import Dict, Any

import pytest
import attrs2bin

# Import test structures for deserialization validation
from test_structures import (
    # Test enums
    BLEPropertiesTest,
    BluetoothAddressTypeTest,
    DataSendTypeTest,
    
    # Test host command structures
    HostCommandConfigurePeripheralTest,
    HostCommandConfigureServiceTest,
    HostCommandConfigureCharacteristicTest,
    HostCommandConfigureCharacteristicReadTest,
    HostCommandNotifyCharacteristicValueTest,
    
    # Test plugin response structures
    PluginDataTest,
    PluginServiceInfoResponseTest,
    PluginCharacteristicInfoResponseTest,
    PluginAuthenticationCompletedResponseTest,
    
    # Integer type test structures
    IntegerTypesTestSmall,
    IntegerTypesTestWithU64I64,
    IntegerTypesTestMixed,
    
    # Utility functions
    validate_test_enum_values,
)

from plugin_host.generated_types import (
    # Constants
    MESSAGE_MAGIC,
    MESSAGE_HEADER_SIZE,
    DEFAULT_PACKET_SIZE,
    
    # Message type mapping
    MessageTypeId,
)


def get_test_data_dir() -> Path:
    """Get the path to the binary test data directory."""
    current_dir = Path(__file__).parent
    return current_dir.parent / "python_regression_test_data" / "binary"


def load_binary_test_file(filename: str) -> bytes:
    """Load a binary test file and return its contents."""
    test_data_dir = get_test_data_dir()
    file_path = test_data_dir / filename
    
    if not file_path.exists():
        pytest.skip(f"Test data file not found: {file_path}")
    
    with open(file_path, 'rb') as f:
        return f.read()


def parse_protocol_header(data: bytes) -> Dict[str, Any]:
    """Parse the protocol header from binary data."""
    if len(data) < MESSAGE_HEADER_SIZE:
        raise ValueError(f"Data too short for header: {len(data)} < {MESSAGE_HEADER_SIZE}")
    
    # Parse header: magic (2 bytes) + type_id (1 byte) + length (2 bytes)
    magic = struct.unpack('<H', data[0:2])[0]  # little-endian uint16
    type_id = data[2]
    length = struct.unpack('<H', data[3:5])[0]  # little-endian uint16
    
    return {
        'magic': magic,
        'type_id': type_id,
        'length': length,
        'payload': data[MESSAGE_HEADER_SIZE:MESSAGE_HEADER_SIZE + length]
    }


def verify_protocol_header(header: Dict[str, Any], expected_type_id: MessageTypeId):
    """Verify that a protocol header is valid."""
    assert header['magic'] == MESSAGE_MAGIC, f"Invalid magic number: 0x{header['magic']:04x}"
    assert header['type_id'] == expected_type_id.value, f"Wrong type ID: {header['type_id']} != {expected_type_id.value}"
    assert header['length'] > 0, "Payload length should be greater than 0"
    assert header['length'] <= DEFAULT_PACKET_SIZE - MESSAGE_HEADER_SIZE, "Payload too large"


def create_python_test_data_and_deserialize(test_struct_class, **kwargs):
    """Create test data in Python format, serialize it, then deserialize it for validation."""
    # Create test instance
    test_instance = test_struct_class(**kwargs)
    
    # Serialize using attrs2bin
    serialized = attrs2bin.serialize(test_instance)
    
    # Deserialize using attrs2bin
    deserialized = attrs2bin.deserialize(serialized, test_struct_class)
    
    # Validate round-trip worked
    assert test_instance == deserialized, f"Round-trip failed for {test_struct_class.__name__}"
    
    return deserialized, serialized


class TestCrossLanguageCompatibility:
    """Test cross-language serialization/deserialization compatibility between Rust and Python."""
    
    def test_rust_to_python_deserialization(self):
        """Test deserialization of Rust-generated binary data into Python structures."""
        # Test HostCommandConfigurePeripheralTest from Rust binary data
        binary_data = load_binary_test_file("test_host_configure_peripheral.bin")
        header = parse_protocol_header(binary_data)
        
        # Verify header first
        verify_protocol_header(header, MessageTypeId.HostCommandConfigurePeripheral)
        
        # Deserialize payload using Python test structure
        result = attrs2bin.deserialize(header['payload'], HostCommandConfigurePeripheralTest)
        
        # Validate deserialized data matches expected Rust values
        assert result.test_name == "TestPeripheral", f"Expected 'TestPeripheral', got '{result.test_name}'"
        assert len(result.test_uuid) == 16, "UUID should be 16 bytes"
        assert result.test_enabled is True, "test_enabled should be True"
        power_level = result.test_power_level.value if hasattr(result.test_power_level, 'value') else result.test_power_level
        assert power_level == 4, f"Expected power_level=4, got {power_level}"
        
        print(f"✅ Cross-language deserialization successful: {result.test_name}, "
              f"uuid={result.test_uuid.hex()[:8]}..., enabled={result.test_enabled}, power={power_level}")
    
    def test_multiple_message_types_deserialization(self):
        """Test that multiple message types can be deserialized correctly."""
        test_cases = [
            ("test_host_configure_peripheral.bin", MessageTypeId.HostCommandConfigurePeripheral, HostCommandConfigurePeripheralTest),
            ("test_host_configure_service.bin", MessageTypeId.HostCommandConfigureService, HostCommandConfigureServiceTest),
            ("test_plugin_data.bin", MessageTypeId.PluginData, PluginDataTest),
            ("test_plugin_service_info_response.bin", MessageTypeId.PluginServiceInfoResponse, PluginServiceInfoResponseTest),
        ]
        
        for filename, expected_type_id, struct_class in test_cases:
            binary_data = load_binary_test_file(filename)
            header = parse_protocol_header(binary_data)
            
            # Verify header
            verify_protocol_header(header, expected_type_id)
            
            # Test that deserialization doesn't crash
            try:
                attrs2bin.deserialize(header['payload'], struct_class)
                print(f"✅ {filename}: Deserialized {struct_class.__name__}")
            except Exception as e:
                pytest.fail(f"Failed to deserialize {filename} as {struct_class.__name__}: {e}")
    
    def test_round_trip_compatibility(self):
        """Test that Python can read Rust data and produce equivalent structures."""
        import uuid as uuid_module
        
        # Create the same data in Python that Rust creates
        expected_name = "TestPeripheral"
        expected_uuid = uuid_module.UUID("12345678-1234-5678-9abc-123456789abc")
        expected_enabled = True
        expected_power = 4
        
        # Load Rust-generated data
        binary_data = load_binary_test_file("test_host_configure_peripheral.bin")
        header = parse_protocol_header(binary_data)
        rust_result = attrs2bin.deserialize(header['payload'], HostCommandConfigurePeripheralTest)
        
        # Create equivalent Python data
        python_result, _ = create_python_test_data_and_deserialize(
            HostCommandConfigurePeripheralTest,
            test_name=expected_name,
            test_uuid=expected_uuid.bytes,
            test_enabled=expected_enabled,
            test_power_level=attrs2bin.U8(expected_power)
        )
        
        # Compare logical equivalence (values should match)
        assert rust_result.test_name == python_result.test_name
        assert rust_result.test_uuid == python_result.test_uuid
        assert rust_result.test_enabled == python_result.test_enabled
        
        rust_power = rust_result.test_power_level.value if hasattr(rust_result.test_power_level, 'value') else rust_result.test_power_level
        python_power = python_result.test_power_level.value if hasattr(python_result.test_power_level, 'value') else python_result.test_power_level
        assert rust_power == python_power
        
        print(f"✅ Cross-language compatibility verified: Rust and Python produce equivalent data structures")


class TestPythonStructures:
    """Test Python test structures independently."""
    
    def test_enum_values_consistency(self):
        """Test that test enum values match the expected Rust implementation."""
        validate_test_enum_values()
        print("✅ All test enum values validated against expected Rust values")
    
    def test_python_serialization_round_trip(self):
        """Test round-trip serialization for Python test structures (attrs2bin only)."""
        import uuid as uuid_module
        
        # Test multiple structures
        test_cases = [
            (HostCommandConfigureServiceTest, {
                'test_service_uuid': uuid_module.uuid4().bytes,
                'test_priority': attrs2bin.U8(100),
                'test_visible': True
            }),
            (HostCommandConfigureCharacteristicTest, {
                'test_char_uuid': uuid_module.uuid4().bytes,
                'test_service_uuid': uuid_module.uuid4().bytes,
                'test_properties': [BLEPropertiesTest.TestRead, BLEPropertiesTest.TestWrite],
                'test_security_level': attrs2bin.U8(2)
            }),
        ]
        
        for struct_class, kwargs in test_cases:
            original = struct_class(**kwargs)
            serialized = attrs2bin.serialize(original)
            deserialized = attrs2bin.deserialize(serialized, struct_class)
            
            # Validate round-trip
            assert original == deserialized, f"Round-trip failed for {struct_class.__name__}"
            
        print("✅ Python round-trip serialization successful for all test structures")
    
    def test_enum_serialization_consistency(self):
        """Test that enum serialization works correctly within Python."""
        # Test BLEPropertiesTest enum
        for prop in BLEPropertiesTest:
            serialized = attrs2bin.serialize(prop)
            deserialized = attrs2bin.deserialize(serialized, BLEPropertiesTest)
            assert prop == deserialized, f"Enum round-trip failed for {prop}"
        
        # Test DataSendTypeTest enum
        for send_type in DataSendTypeTest:
            serialized = attrs2bin.serialize(send_type)
            deserialized = attrs2bin.deserialize(serialized, DataSendTypeTest)
            assert send_type == deserialized, f"Enum round-trip failed for {send_type}"
        
        print("✅ All test enums pass Python round-trip serialization")
    
    def test_integer_types_round_trip(self):
        """Test round-trip serialization for all integer types."""
        # Test IntegerTypesTestSmall
        small_test = IntegerTypesTestSmall(
            test_u8=attrs2bin.U8(255),
            test_u16=attrs2bin.U16(65535),
            test_u32=attrs2bin.U32(4294967295),
            test_i8=attrs2bin.I8(-128),
            test_i16=attrs2bin.I16(-32768),
            test_i32=attrs2bin.I32(-2147483648),
            test_f32=attrs2bin.Float32(3.14159),
            test_f64=attrs2bin.Float64(2.718281828459045),
        )
        serialized = attrs2bin.serialize(small_test)
        deserialized = attrs2bin.deserialize(serialized, IntegerTypesTestSmall)
        
        # Check integer fields for exact equality
        assert small_test.test_u8 == deserialized.test_u8
        assert small_test.test_u16 == deserialized.test_u16  
        assert small_test.test_u32 == deserialized.test_u32
        assert small_test.test_i8 == deserialized.test_i8
        assert small_test.test_i16 == deserialized.test_i16
        assert small_test.test_i32 == deserialized.test_i32
        
        # Check floating-point fields with approximate equality
        assert abs(small_test.test_f32 - deserialized.test_f32) < 1e-5
        assert abs(small_test.test_f64 - deserialized.test_f64) < 1e-14
        
        # Test IntegerTypesTestWithU64I64
        u64_i64_test = IntegerTypesTestWithU64I64(
            test_u64=attrs2bin.UnsignedInt(18446744073709551615),  # Max U64
            test_i64=attrs2bin.SignedInt(-9223372036854775808),    # Min I64
            test_u16=attrs2bin.U16(12345),
            test_i16=attrs2bin.I16(-12345),
            test_enabled=True,
        )
        serialized = attrs2bin.serialize(u64_i64_test)
        deserialized = attrs2bin.deserialize(serialized, IntegerTypesTestWithU64I64)
        assert u64_i64_test == deserialized, "Integer types U64/I64 round-trip failed"
        
        # Test IntegerTypesTestMixed
        mixed_test = IntegerTypesTestMixed(
            test_u8=attrs2bin.U8(42),
            test_i8=attrs2bin.I8(-42),
            test_u16=attrs2bin.U16(1234),
            test_i16=attrs2bin.I16(-1234),
            test_f32=attrs2bin.Float32(1.414213562373095),  # sqrt(2)
            test_bool=True,
        )
        serialized = attrs2bin.serialize(mixed_test)
        deserialized = attrs2bin.deserialize(serialized, IntegerTypesTestMixed)
        
        # Check integer and bool fields for exact equality
        assert mixed_test.test_u8 == deserialized.test_u8
        assert mixed_test.test_i8 == deserialized.test_i8
        assert mixed_test.test_u16 == deserialized.test_u16
        assert mixed_test.test_i16 == deserialized.test_i16
        assert mixed_test.test_bool == deserialized.test_bool
        
        # Check floating-point field with approximate equality
        assert abs(mixed_test.test_f32 - deserialized.test_f32) < 1e-5
        
        print("✅ All integer types pass Python round-trip serialization")
    
    def test_integer_types_cross_language_compatibility(self):
        """Test that Python can deserialize Rust-generated integer type data."""
        # Test IntegerTypesTestSmall
        try:
            small_data = load_binary_test_file("test_integer_types_small.bin")
            header = parse_protocol_header(small_data)
            small_result = attrs2bin.deserialize(header['payload'], IntegerTypesTestSmall)
            
            # Validate values match what Rust generates
            assert small_result.test_u8 == 255
            assert small_result.test_u16 == 65535
            assert small_result.test_u32 == 4294967295
            assert small_result.test_i8 == -128
            assert small_result.test_i16 == -32768
            assert small_result.test_i32 == -2147483648
            assert abs(small_result.test_f32 - 3.14159) < 1e-5  # f32 precision
            assert abs(small_result.test_f64 - 2.718281828459045) < 1e-14  # f64 precision
            
            print("✅ IntegerTypesTestSmall cross-language compatibility verified")
        except FileNotFoundError:
            pytest.skip("Integer types small test data not generated yet")
        
        # Test IntegerTypesTestWithU64I64
        try:
            u64_i64_data = load_binary_test_file("test_integer_types_u64_i64.bin")
            header = parse_protocol_header(u64_i64_data)
            u64_i64_result = attrs2bin.deserialize(header['payload'], IntegerTypesTestWithU64I64)
            
            # Validate values match what Rust generates
            assert u64_i64_result.test_u64 == 18446744073709551615  # Max U64
            assert u64_i64_result.test_i64 == -9223372036854775808   # Min I64
            assert u64_i64_result.test_u16 == 12345
            assert u64_i64_result.test_i16 == -12345
            assert u64_i64_result.test_enabled is True
            
            print("✅ IntegerTypesTestWithU64I64 cross-language compatibility verified")
        except FileNotFoundError:
            pytest.skip("Integer types U64/I64 test data not generated yet")
        
        # Test IntegerTypesTestMixed
        try:
            mixed_data = load_binary_test_file("test_integer_types_mixed.bin")
            header = parse_protocol_header(mixed_data)
            mixed_result = attrs2bin.deserialize(header['payload'], IntegerTypesTestMixed)
            
            # Validate values match what Rust generates
            assert mixed_result.test_u8 == 42
            assert mixed_result.test_i8 == -42
            assert mixed_result.test_u16 == 1234
            assert mixed_result.test_i16 == -1234
            assert abs(mixed_result.test_f32 - 1.414213562373095) < 1e-5  # f32 precision
            assert mixed_result.test_bool is True
            
            print("✅ IntegerTypesTestMixed cross-language compatibility verified")
        except FileNotFoundError:
            pytest.skip("Integer types mixed test data not generated yet")
        
        print("✅ All integer types cross-language compatibility verified")


class TestListAndBytesDeserialization:
    """Test correct deserialization of lists and bytes with length prefixes from Rust-generated data."""
    
    def test_characteristic_properties_list_deserialization(self):
        """Test deserialization of characteristic properties list from Rust binary data."""
        # Load the Rust-generated binary with a 3-element properties list
        binary_data = load_binary_test_file("test_host_configure_characteristic.bin")
        header = parse_protocol_header(binary_data)
        
        result = attrs2bin.deserialize(header['payload'], HostCommandConfigureCharacteristicTest)
        
        # Verify the exact values from Rust generate_test_data.rs lines 260-263
        assert len(result.test_properties) == 3, "Should have exactly 3 properties"
        assert result.test_properties[0] == BLEPropertiesTest.TestRead, "First property should be TestRead (10)"
        assert result.test_properties[1] == BLEPropertiesTest.TestWrite, "Second property should be TestWrite (11)"
        assert result.test_properties[2] == BLEPropertiesTest.TestNotify, "Third property should be TestNotify (12)"
        
        print("✅ Characteristic properties list (3 elements) deserialized correctly from Rust data")
    
    def test_characteristic_read_default_value_list(self):
        """Test deserialization of default value byte list from Rust binary data."""
        # Load the Rust-generated binary with default_value = [0x48, 0x65, 0x6c, 0x6c, 0x6f] ("Hello")
        binary_data = load_binary_test_file("test_host_configure_characteristic_read.bin")
        header = parse_protocol_header(binary_data)
        
        result = attrs2bin.deserialize(header['payload'], HostCommandConfigureCharacteristicReadTest)
        
        # Verify the exact values from Rust generate_test_data.rs lines 279-281
        assert len(result.test_default_value) == 5, "Should have 5 bytes ('Hello')"
        expected_hello = [0x48, 0x65, 0x6c, 0x6c, 0x6f]  # "Hello" in hex
        for i, byte_val in enumerate(result.test_default_value):
            val = byte_val.value if hasattr(byte_val, 'value') else byte_val
            assert val == expected_hello[i], f"Byte {i} should be 0x{expected_hello[i]:02x}, got {val}"
        
        # Convert to string to verify it's "Hello"
        bytes_as_string = bytes([b.value if hasattr(b, 'value') else b for b in result.test_default_value])
        assert bytes_as_string == b"Hello", "Default value should be 'Hello'"
        
        print("✅ Default value byte list ('Hello') deserialized correctly from Rust data")
    
    def test_notification_value_and_device_address_lists(self):
        """Test deserialization of notification value and device address lists from Rust binary data."""
        # Load the Rust-generated binary with notification_value = [0x01, 0x02, 0x03, 0x04, 0x05]
        # and device_address = [0x11, 0x22, 0x33, 0x44, 0x55, 0x66] (now as HeaplessVec)
        binary_data = load_binary_test_file("test_host_notify_characteristic_value.bin")
        header = parse_protocol_header(binary_data)
        
        result = attrs2bin.deserialize(header['payload'], HostCommandNotifyCharacteristicValueTest)
        
        # Verify the notification value from lines 326-328
        assert len(result.test_notification_value) == 5, "Should have 5 bytes in notification value"
        expected_values = [0x01, 0x02, 0x03, 0x04, 0x05]
        for i, byte_val in enumerate(result.test_notification_value):
            val = byte_val.value if hasattr(byte_val, 'value') else byte_val
            assert val == expected_values[i], f"Notification byte {i} should be 0x{expected_values[i]:02x}, got {val}"
        
        # Verify the device address (now HeaplessVec from lines 330-333)
        expected_address = [0x11, 0x22, 0x33, 0x44, 0x55, 0x66]
        assert len(result.test_device_address) == 6, "Device address should be 6 bytes"
        
        # Device address is now bytes with length prefix
        for i, byte_val in enumerate(result.test_device_address):
            assert byte_val == expected_address[i], f"Address byte {i} should be 0x{expected_address[i]:02x}, got 0x{byte_val:02x}"
        
        print("✅ Notification value list and device address (with length prefix) deserialized correctly")
    
    def test_plugin_data_variable_length_bytes(self):
        """Test deserialization of variable-length bytes payload from Rust binary data."""
        # Load the Rust-generated binary with payload = b"Test data"
        binary_data = load_binary_test_file("test_plugin_data.bin")
        header = parse_protocol_header(binary_data)
        
        result = attrs2bin.deserialize(header['payload'], PluginDataTest)
        
        # Verify the exact payload from Rust generate_test_data.rs line 351
        assert result.test_payload == b"Test data", "Payload should be 'Test data'"
        assert len(result.test_payload) == 9, "Payload should be 9 bytes long"
        
        # Also verify other fields
        assert result.test_send_type == DataSendTypeTest.TestWrite, "Data type should be TestWrite (32)"
        assert result.test_timestamp == 123, "Timestamp should be 123"
        assert result.test_connection_handle == 1, "Connection handle should be 1"
        
        print("✅ Variable-length bytes payload ('Test data') deserialized correctly")
    
    def test_service_info_characteristic_uuids_list(self):
        """Test deserialization of list of UUIDs from Rust binary data."""
        # Load the Rust-generated binary with 2 characteristic UUIDs
        binary_data = load_binary_test_file("test_plugin_service_info_response.bin")
        header = parse_protocol_header(binary_data)
        
        result = attrs2bin.deserialize(header['payload'], PluginServiceInfoResponseTest)
        
        # Verify the exact UUIDs from Rust generate_test_data.rs lines 375-381
        assert len(result.test_characteristic_uuids) == 2, "Should have 2 characteristic UUIDs"
        
        import uuid as uuid_module
        expected_uuids = [
            uuid_module.UUID("abcdef01-2345-6789-abcd-ef0123456789").bytes,
            uuid_module.UUID("11111111-2222-3333-4444-555555555555").bytes,
        ]
        
        for i, uuid_bytes in enumerate(result.test_characteristic_uuids):
            assert uuid_bytes == expected_uuids[i], f"UUID {i} should match expected"
            assert len(uuid_bytes) == 16, f"UUID {i} should be 16 bytes"
        
        # Also verify the count field
        assert result.test_characteristic_count == 2, "Characteristic count should be 2"
        assert result.test_service_exists is True, "Service exists should be true"
        assert result.test_service_active is True, "Service active should be true"
        
        print("✅ List of characteristic UUIDs (2 UUIDs) deserialized correctly")
    
    def test_characteristic_info_properties_list(self):
        """Test deserialization of characteristic info properties list from Rust binary data."""
        # Load the Rust-generated binary with 2-element properties list
        binary_data = load_binary_test_file("test_plugin_characteristic_info_response.bin")
        header = parse_protocol_header(binary_data)
        
        result = attrs2bin.deserialize(header['payload'], PluginCharacteristicInfoResponseTest)
        
        # Verify the exact values from Rust generate_test_data.rs lines 397-399
        assert len(result.test_properties) == 2, "Should have exactly 2 properties"
        assert result.test_properties[0] == BLEPropertiesTest.TestRead, "First property should be TestRead (10)"
        assert result.test_properties[1] == BLEPropertiesTest.TestNotify, "Second property should be TestNotify (12)"
        
        # Also verify other fields
        assert result.test_char_exists is True, "Char exists should be true"
        assert result.test_value_length == 20, "Value length should be 20"
        assert result.test_client_config == 1, "Client config should be 1"
        
        print("✅ Characteristic info properties list (2 elements) deserialized correctly")
    
    def test_authentication_device_address_with_length_prefix(self):
        """Test deserialization of device address with length prefix from Rust binary data."""
        # Load the Rust-generated binary with device_address = [0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff]
        # Now using HeaplessVec instead of fixed array
        binary_data = load_binary_test_file("test_plugin_authentication_completed_response.bin")
        header = parse_protocol_header(binary_data)
        
        result = attrs2bin.deserialize(header['payload'], PluginAuthenticationCompletedResponseTest)
        
        # Verify the exact address from Rust generate_test_data.rs lines 421-424
        expected_address = [0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff]
        assert len(result.test_device_address) == 6, "Device address should be 6 bytes"
        
        # Device address is now bytes with length prefix
        for i, byte_val in enumerate(result.test_device_address):
            assert byte_val == expected_address[i], f"Address byte {i} should be 0x{expected_address[i]:02x}, got 0x{byte_val:02x}"
        
        # Also verify other fields
        assert result.test_address_type == BluetoothAddressTypeTest.TestRandom, "Address type should be TestRandom (21)"
        assert result.test_auth_success is True, "Auth success should be true"
        assert result.test_auth_level == 3, "Auth level should be 3"
        assert result.test_bond_created is True, "Bond created should be true"
        
        print("✅ Device address with length prefix deserialized correctly")
    
    def test_empty_lists_round_trip(self):
        """Test that empty lists deserialize correctly in Python round-trip."""
        import uuid as uuid_module
        
        # Test empty properties list
        char_empty = HostCommandConfigureCharacteristicTest(
            test_char_uuid=uuid_module.uuid4().bytes,
            test_service_uuid=uuid_module.uuid4().bytes,
            test_properties=[],  # Empty list
            test_security_level=attrs2bin.U8(0)
        )
        
        serialized = attrs2bin.serialize(char_empty)
        deserialized = attrs2bin.deserialize(serialized, HostCommandConfigureCharacteristicTest)
        
        assert isinstance(deserialized.test_properties, list), "Properties should be a list"
        assert len(deserialized.test_properties) == 0, "Properties list should be empty"
        
        # Test empty characteristic UUIDs list
        service_empty = PluginServiceInfoResponseTest(
            test_service_uuid=uuid_module.uuid4().bytes,
            test_characteristic_uuids=[],  # Empty list
            test_service_exists=False,
            test_service_active=False,
            test_characteristic_count=attrs2bin.U8(0)
        )
        
        serialized = attrs2bin.serialize(service_empty)
        deserialized = attrs2bin.deserialize(serialized, PluginServiceInfoResponseTest)
        
        assert isinstance(deserialized.test_characteristic_uuids, list), "UUIDs should be a list"
        assert len(deserialized.test_characteristic_uuids) == 0, "UUIDs list should be empty"
        
        # Test empty bytes payload
        plugin_empty = PluginDataTest(
            test_source_id=uuid_module.uuid4().bytes,
            test_send_type=DataSendTypeTest.TestWrite,
            test_payload=b"",  # Empty bytes
            test_timestamp=attrs2bin.U8(0),
            test_connection_handle=attrs2bin.U8(0)
        )
        
        serialized = attrs2bin.serialize(plugin_empty)
        deserialized = attrs2bin.deserialize(serialized, PluginDataTest)
        
        assert isinstance(deserialized.test_payload, bytes), "Payload should be bytes"
        assert len(deserialized.test_payload) == 0, "Payload should be empty"
        
        print("✅ Empty lists and bytes handle length prefixes correctly")
    
    def test_maximum_capacity_lists(self):
        """Test lists at their maximum capacity with proper length prefixes."""
        import uuid as uuid_module
        
        # Test max capacity for characteristic UUIDs list (HeaplessVec<Uuid, 8>)
        max_uuids = [uuid_module.uuid4().bytes for _ in range(8)]
        service_info = PluginServiceInfoResponseTest(
            test_service_uuid=uuid_module.uuid4().bytes,
            test_characteristic_uuids=max_uuids,  # 8 UUIDs (max capacity)
            test_service_exists=True,
            test_service_active=True,
            test_characteristic_count=attrs2bin.U8(8)
        )
        
        serialized = attrs2bin.serialize(service_info)
        deserialized = attrs2bin.deserialize(serialized, PluginServiceInfoResponseTest)
        
        assert len(deserialized.test_characteristic_uuids) == 8, "Should have 8 UUIDs"
        for i, uuid_bytes in enumerate(deserialized.test_characteristic_uuids):
            assert uuid_bytes == max_uuids[i], f"UUID {i} should match"
            assert len(uuid_bytes) == 16, f"UUID {i} should be 16 bytes"
        
        # Test max capacity for default value (HeaplessVec<u8, 16>)
        max_default = [attrs2bin.U8(i) for i in range(16)]
        char_read_max = HostCommandConfigureCharacteristicReadTest(
            test_char_uuid=uuid_module.uuid4().bytes,
            test_service_uuid=uuid_module.uuid4().bytes,
            test_default_value=max_default,  # 16 bytes (max capacity)
            test_read_permissions=attrs2bin.U8(1)
        )
        
        serialized = attrs2bin.serialize(char_read_max)
        deserialized = attrs2bin.deserialize(serialized, HostCommandConfigureCharacteristicReadTest)
        
        assert len(deserialized.test_default_value) == 16, "Should have 16 bytes"
        for i, value in enumerate(deserialized.test_default_value):
            assert value == i, f"Byte {i} should have value {i}"
        
        # Test max capacity for notification value (HeaplessVec<u8, 20>)
        max_notification = [attrs2bin.U8(i % 256) for i in range(20)]
        notify_max = HostCommandNotifyCharacteristicValueTest(
            test_device_address=bytes([i % 256 for i in range(6)]),  # Now bytes with length prefix
            test_address_type=BluetoothAddressTypeTest.TestPublic,
            test_char_uuid=uuid_module.uuid4().bytes,
            test_service_uuid=uuid_module.uuid4().bytes,
            test_notification_value=max_notification,  # 20 bytes (max capacity)
            test_confirm_required=False
        )
        
        serialized = attrs2bin.serialize(notify_max)
        deserialized = attrs2bin.deserialize(serialized, HostCommandNotifyCharacteristicValueTest)
        
        assert len(deserialized.test_notification_value) == 20, "Should have 20 bytes"
        for i, value in enumerate(deserialized.test_notification_value):
            assert value == i % 256, f"Byte {i} should have value {i % 256}"
        
        print("✅ Maximum capacity lists with length prefixes deserialized correctly")


class TestBinaryDataIntegrity:
    """Test the integrity and structure of generated binary data."""
    
    def test_binary_data_integrity(self):
        """Test that all binary files exist, have correct sizes, and valid headers."""
        expected_files = [
            "test_host_configure_peripheral.bin",
            "test_host_configure_service.bin", 
            "test_host_configure_characteristic.bin",
            "test_plugin_data.bin",
            "test_plugin_service_info_response.bin",
        ]
        
        test_data_dir = get_test_data_dir()
        
        for filename in expected_files:
            file_path = test_data_dir / filename
            
            # Check file exists
            assert file_path.exists(), f"Missing test data file: {filename}"
            
            # Check file size
            file_size = file_path.stat().st_size
            assert file_size == DEFAULT_PACKET_SIZE, f"File {filename} has wrong size: {file_size} != {DEFAULT_PACKET_SIZE}"
            
            # Check header magic number
            with open(file_path, 'rb') as f:
                data = f.read()
            
            header = parse_protocol_header(data)
            assert header['magic'] == MESSAGE_MAGIC, f"File {filename} has wrong magic: 0x{header['magic']:04x}"
            
        print(f"✅ All {len(expected_files)} binary files pass integrity checks")


def test_compatibility_status():
    """Document the current cross-language serialization compatibility status."""
    print("\n" + "="*60)
    print("CROSS-LANGUAGE SERIALIZATION COMPATIBILITY")
    print("="*60)
    print("Status: Rust bincode and Python attrs2bin are now COMPATIBLE!")
    print("This test suite validates:")
    print("1. ✅ Protocol headers (magic, type_id, length) - COMPATIBLE")
    print("2. ✅ Message structure validation - COMPATIBLE") 
    print("3. ✅ Python attrs2bin round-trip - WORKS")
    print("4. ✅ Rust bincode round-trip - WORKS (tested in Rust)")
    print("5. ✅ Cross-language payload deserialization - COMPATIBLE!")
    print("\nCompatibility achieved by:")
    print("- Using only U8 types for numeric values (avoiding u16, i8, u64)")
    print("- Consistent string and UUID handling")
    print("- Matching enum value assignments")
    print("- Identical struct field ordering")
    print("\nFull interoperability is now possible between Rust and Python!")
    print("="*60)


def test_regression_suite_info():
    """Print information about the regression test suite."""
    test_data_dir = get_test_data_dir()
    
    print("\n" + "="*60)
    print("STREAMLINED PROTOCOL REGRESSION TEST SUITE")
    print("="*60)
    print(f"Test data directory: {test_data_dir}")
    print(f"Generated binary files: {len(list(test_data_dir.glob('*.bin')))}")
    print(f"Protocol magic number: 0x{MESSAGE_MAGIC:04x}")
    print(f"Header size: {MESSAGE_HEADER_SIZE} bytes")
    print(f"Packet size: {DEFAULT_PACKET_SIZE} bytes")
    
    print("\nTest coverage:")
    print("  ✅ Cross-language deserialization (Rust → Python)")
    print("  ✅ Python structure round-trip serialization")  
    print("  ✅ Binary data integrity validation")
    print("  ✅ Protocol header validation")
    print("  ✅ Enum consistency verification")
    print("="*60)