[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --no-stub -s 8mb -f 80mhz"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort", "core"]

[env]
MCU = "esp32s3"
ESP_IDF_VERSION = "v5.2.3"
# Make sure you run . $HOME/export-esp.sh if needed
TARGET_CC="xtensa-esp32s3-elf-cc"
TARGET_AR="xtensa-esp32s3-elf-ar"

[alias]
r = "run --release"
