[package]
name = "plugin-std"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "plugin-std"
path = "src/bin/main.rs"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"
debug = true    # Symbols are nice and they don't increase the size on Flash

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
## Files in shared directory
lib_utils = {path = "../lib_utils"}
protocol = {path = "../protocol"}
# device-cherry = {path = "../device-cherry"}
## Crates
# esp32-nimble = "0.11.0"
# log = "0.4.27"
esp-idf-sys = { version = "0.36.1", default-features = false }
esp-idf-svc = { version = "0.51", features = ["alloc", "binstart", "embassy-time-driver", "embassy-sync"], default-features = false }
static_cell = "2"
heapless = "0.8.0"
embassy-futures = "0.1.1"
esp-println = {version = "0.12.0", features = ["esp32s3","jtag-serial"], default-features = false}

[build-dependencies]
embuild = "0.33"


[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "cherry-embedded/cherryusb", version = "1.5.1~5" }
# component_dirs = "components/cherryusb"
bindings_header = "cherry_usb_device_bindings.h"
bindings_module = "cherry_device"
