[package]
name = "plugin-std"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "plugin-std"
path = "src/bin/main.rs"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"
debug = true    # Symbols are nice and they don't increase the size on Flash

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
## Custom
lib_utils = {path = "../lib_utils"}
protocol = {path = "../protocol"}
device-cherry = {path = "../device-cherry"}
plugin_state_machine_std = { path = "../plugin_state_machine_std" }
## Crates
esp32-nimble ={version =  "0.11.0", default-features = false, features = ["no_std"]}
log = {version = "0.4.27", default-features = false}
esp-idf-sys = { version = "0.36.1", default-features = false }
esp-idf-svc = { version = "0.51", features = ["binstart", "embassy-sync"], default-features = false }

static_cell = "2"
heapless = "0.8.0"
embassy-futures = "0.1.1"
ringbuffer = {version = "0.15.0", default-features = false}
embassy-sync = "0.7.0"
uuid = { version = "1.17.0", default-features = false, features = ["serde"] }
thiserror-no-std = "2.0.2"

[build-dependencies]
embuild = "0.33"
