# GENERATED CODE - DO NOT EDIT MANUALLY
# This file is automatically generated from the Rust protocol library
# Source: protocol/src/io.rs and protocol/src/io_types.rs
# Generator: codegen/src/bin/generate_python.rs

import attrs2bin
import attr
from enum import Enum
from typing import List, Optional

# ==================== PROTOCOL HASH ====================
# Hash of all protocol source files - used to detect when regeneration is needed
PROTOCOL_HASH = "76f6c48d00c3004c3bcc143346189bfb7be6a717ca5415d7deba8f9c1fc99fb6"

# ==================== CONSTANTS ====================


# Magic number for message integrity validation (0xDEAD)  This constant magic n...
MESSAGE_MAGIC = 0xDEAD


# Maximum size for BLE peripheral device names  This constant defines the maxim...
MAX_NAME_SIZE = 30


# Default USB packet size for communication  This represents the standard trans...
DEFAULT_PACKET_SIZE = 256


# Maximum size for characteristic properties
MAX_PROPERTIES = 4


# Maximum characteritics per service
MAX_CHARACTERISTICS_PER_SERVICE = 16


# Derived constants
MESSAGE_MAGIC_BYTES = 2  # Size in bytes of the magic number field
MESSAGE_TYPE_ID_BYTES = 1  # Size in bytes of the message type identifier field  
DATA_BYTES_LENGTH_IN_BYTES = 2  # Size in bytes of the payload length field

# Message protocol constants
MESSAGE_HEADER_SIZE = MESSAGE_MAGIC_BYTES + MESSAGE_TYPE_ID_BYTES + DATA_BYTES_LENGTH_IN_BYTES  # 5 bytes

# ==================== ENUMS ====================


class MessageTypeId(Enum):
    """Message type identifiers for efficient command dispatch  This enum defines un..."""
    # Configure BLE peripheral device with name and UUID
    HostCommandConfigurePeripheral: attrs2bin.U8 = 0x01
    # Create a new BLE service with specified UUID
    HostCommandConfigureService: attrs2bin.U8 = 0x02
    # Create a BLE characteristic with properties
    HostCommandConfigureCharacteristic: attrs2bin.U8 = 0x03
    # Configure characteristic for read operations with default value
    HostCommandConfigureCharacteristicRead: attrs2bin.U8 = 0x04
    # Query information about a BLE service
    HostCommandGetServiceInfo: attrs2bin.U8 = 0x05
    # Query information about a BLE characteristic
    HostCommandGetCharacteristicInfo: attrs2bin.U8 = 0x06
    # Start BLE advertising with optional multi-connect support
    HostCommandStartAdvertisement: attrs2bin.U8 = 0x07
    # Send notification/indication to connected BLE client
    HostCommandNotifyCharacteristicValue: attrs2bin.U8 = 0x08
    # Data forwarded from BLE client to host
    PluginData: attrs2bin.U8 = 0x80
    # Configuration error response from plugin
    PluginConfigurationError: attrs2bin.U8 = 0x81
    # Service information response with characteristic list
    PluginServiceInfoResponse: attrs2bin.U8 = 0x82
    # Characteristic information response with properties
    PluginCharacteristicInfoResponse: attrs2bin.U8 = 0x83
    # Authentication completed response from plugin
    PluginAuthenticationCompletedResponse: attrs2bin.U8 = 0x84


class BLEProperties(Enum):
    """Properties enumeration for BLE characteristics."""
    # Read property
    READ: attrs2bin.U8 = 0
    # Write property
    WRITE: attrs2bin.U8 = 1
    # Write without response property
    WriteNoRsp: attrs2bin.U8 = 2
    # Notify property
    NOTIFY: attrs2bin.U8 = 3
    # Indicate property
    INDICATE: attrs2bin.U8 = 4


class BluetoothAddressType(Enum):
    """Bluetooth Device address type"""
    # Public address
    Public: attrs2bin.U8 = 0
    # Random address
    Random: attrs2bin.U8 = 1
    # Public ID address
    PublicID: attrs2bin.U8 = 2
    # Random ID address
    RandomID: attrs2bin.U8 = 3


class PluginDataSendType(Enum):
    """Represents the send type of the data. Was it due to a write event (central -&gt;..."""
    # Notified from the central bluetooth device
    Notify: attrs2bin.U8 = 0
    # Read attempt from the central bluetooth device
    Read: attrs2bin.U8 = 1
    # Written from the central bluetooth device
    Write: attrs2bin.U8 = 2


class PluginConfigurationError(Enum):
    """Represents the error that can occur during plugin configuration"""
    # The peripheral name is too long
    PeripheralNameTooLong: attrs2bin.U8 = 0
    # The peripheral UUID is invalid
    InvalidPeripheralUuid: attrs2bin.U8 = 1
    # The service UUID is invalid
    InvalidServiceUuid: attrs2bin.U8 = 2
    # The characteristic UUID is invalid
    InvalidCharacteristicUuid: attrs2bin.U8 = 3
    # Advertisement without proper peripheral configuration
    AdvertisementWithoutPeripheralConfiguration: attrs2bin.U8 = 4
    # Service without proper peripheral configuration
    ServiceWithoutPeripheralConfiguration: attrs2bin.U8 = 5
    # Characteristic without proper service configuration
    CharacteristicWithoutServiceConfiguration: attrs2bin.U8 = 6


# ==================== MESSAGE STRUCTURES ====================

@attr.s(auto_attribs=True)
class HostCommandConfigurePeripheral:
    """Host command. Configure peripheral
    
    Attributes:
        name:Peripheral name
        uuid:Peripheral UUID
    """
    name: str
    uuid: str

@attr.s(auto_attribs=True)
class HostCommandConfigureService:
    """Host command. Configure service
    
    Attributes:
        uuid:Service UUID
    """
    uuid: str

@attr.s(auto_attribs=True)
class HostCommandConfigureCharacteristic:
    """Host command. Configure characteristic
    
    Attributes:
        uuid:Characteristic UUID
        service_uuid:Service UUID this characteristic belongs to
        properties:Properties of the characteristic (read, write, notify, etc.)
    """
    uuid: str
    service_uuid: str
    properties: List[BLEProperties]

@attr.s(auto_attribs=True)
class HostCommandConfigureCharacteristicRead:
    """Host command. Configure characteristic read
    
    Attributes:
        uuid:Characteristic UUID
        service_uuid:Service UUID this characteristic belongs to
        value:Read value
    """
    uuid: str
    service_uuid: str
    value: List[attrs2bin.U8]

@attr.s(auto_attribs=True)
class HostCommandGetServiceInfo:
    """Host command. Get service info
    
    Attributes:
        uuid:Service UUID
    """
    uuid: str

@attr.s(auto_attribs=True)
class HostCommandGetCharacteristicInfo:
    """Host command. Get characteristic info
    
    Attributes:
        characteristic_uuid:Characteristic UUID
        service_uuid:Service UUID this characteristic belongs to
    """
    characteristic_uuid: str
    service_uuid: str

@attr.s(auto_attribs=True)
class HostCommandStartAdvertisement:
    """Host command. Start advertisement
    
    Attributes:
        allow_multi_connect:Allow multiple central connections
    """
    allow_multi_connect: bool

@attr.s(auto_attribs=True)
class HostCommandNotifyCharacteristicValue:
    """Host command. Notify characteristic value
    
    Attributes:
        address:Device Address.
        address_type:Address type
        characteristic_uuid:Characteristic UUID
        service_uuid:Service UUID this characteristic belongs to
        value:Value to notify
    """
    address: List[attrs2bin.U8]
    address_type: BluetoothAddressType
    characteristic_uuid: str
    service_uuid: str
    value: List[attrs2bin.U8]

@attr.s(auto_attribs=True)
class PluginData:
    """Plugin data
    
    Attributes:
        src_id:Source peripheral id that this data is orginating from.
        send_type:Send type of the data
        data:Actual command type
    """
    src_id: str
    send_type: PluginDataSendType
    data: bytes

@attr.s(auto_attribs=True)
class PluginServiceInfoResponse:
    """Service information response
    
    Attributes:
        service_uuid:Service UUID
        characteristic_uuids:List of characteristic UUIDs in this service
        exists:Whether the service exists
    """
    service_uuid: str
    characteristic_uuids: List[str]
    exists: bool

@attr.s(auto_attribs=True)
class PluginCharacteristicInfoResponse:
    """Characteristic information response
    
    Attributes:
        characteristic_uuid:Characteristic UUID
        service_uuid:Service UUID this characteristic belongs to
        properties:Properties of the characteristic (read, write, notify, etc.)
        exists:Whether the characteristic exists
    """
    characteristic_uuid: str
    service_uuid: str
    properties: List[BLEProperties]
    exists: bool

@attr.s(auto_attribs=True)
class PluginAuthenticationCompletedResponse:
    """Plugin authentication completed response
    
    Attributes:
        address:Address of the device that was authenticated
        address_type:Address type
        success:Whether the authentication was successful
    """
    address: List[attrs2bin.U8]
    address_type: BluetoothAddressType
    success: bool

# ==================== MESSAGE TYPE MAPPING ====================

# Map message types to their type IDs
MESSAGE_TYPE_MAP = {
    HostCommandConfigurePeripheral: MessageTypeId.HostCommandConfigurePeripheral,
    HostCommandConfigureService: MessageTypeId.HostCommandConfigureService,
    HostCommandConfigureCharacteristic: MessageTypeId.HostCommandConfigureCharacteristic,
    HostCommandConfigureCharacteristicRead: MessageTypeId.HostCommandConfigureCharacteristicRead,
    HostCommandGetServiceInfo: MessageTypeId.HostCommandGetServiceInfo,
    HostCommandGetCharacteristicInfo: MessageTypeId.HostCommandGetCharacteristicInfo,
    HostCommandStartAdvertisement: MessageTypeId.HostCommandStartAdvertisement,
    HostCommandNotifyCharacteristicValue: MessageTypeId.HostCommandNotifyCharacteristicValue,
    PluginData: MessageTypeId.PluginData,
    PluginServiceInfoResponse: MessageTypeId.PluginServiceInfoResponse,
    PluginCharacteristicInfoResponse: MessageTypeId.PluginCharacteristicInfoResponse,
    PluginAuthenticationCompletedResponse: MessageTypeId.PluginAuthenticationCompletedResponse,
}

# Reverse map for easy lookup
TYPE_ID_TO_MESSAGE_TYPE = {v: k for k, v in MESSAGE_TYPE_MAP.items()}