# GENERATED CODE - DO NOT EDIT MANUALLY
# This file is automatically generated from the Rust protocol library
# Source: protocol/src/io.rs and protocol/src/io_types.rs
# Generator: codegen/src/bin/generate_python.rs

import attrs2bin
import attr
from enum import Enum
from typing import List, Optional

# ==================== CONSTANTS ====================


# Magic number for message integrity validation (0xDEAD)  This constant magic n...
MESSAGE_MAGIC = 0xDEAD


# Maximum size for BLE peripheral device names  This constant defines the maxim...
MAX_NAME_SIZE = 30


# Default USB packet size for communication  This represents the standard trans...
DEFAULT_PACKET_SIZE = 256


# Derived constants
MESSAGE_MAGIC_BYTES = 2  # Size in bytes of the magic number field
MESSAGE_TYPE_ID_BYTES = 1  # Size in bytes of the message type identifier field  
DATA_BYTES_LENGTH_IN_BYTES = 2  # Size in bytes of the payload length field

# Message protocol constants
MESSAGE_HEADER_SIZE = MESSAGE_MAGIC_BYTES + MESSAGE_TYPE_ID_BYTES + DATA_BYTES_LENGTH_IN_BYTES  # 5 bytes

# ==================== ENUMS ====================


class MessageTypeId(Enum):
    """Message type identifiers for efficient command dispatch  This enum defines un..."""
    # Configure BLE peripheral device with name and UUID
    HostCommandConfigurePeripheral = 0x01
    # Create a new BLE service with specified UUID
    HostCommandConfigureService = 0x02
    # Create a BLE characteristic with properties
    HostCommandConfigureCharacteristic = 0x03
    # Configure characteristic for read operations with default value
    HostCommandConfigureCharacteristicRead = 0x04
    # Query information about a BLE service
    HostCommandGetServiceInfo = 0x05
    # Query information about a BLE characteristic
    HostCommandGetCharacteristicInfo = 0x06
    # Start BLE advertising with optional multi-connect support
    HostCommandStartAdvertisement = 0x07
    # Send notification/indication to connected BLE client
    HostCommandNotifyCharacteristicValue = 0x08
    # Data forwarded from BLE client to host
    PluginData = 0x80
    # Configuration error response from plugin
    PluginConfigurationError = 0x81
    # Service information response with characteristic list
    PluginServiceInfoResponse = 0x82
    # Characteristic information response with properties
    PluginCharacteristicInfoResponse = 0x83


# ==================== MESSAGE STRUCTURES ====================

# ==================== MESSAGE TYPE MAPPING ====================

# Map message types to their type IDs
MESSAGE_TYPE_MAP = {
}

# Reverse map for easy lookup
TYPE_ID_TO_MESSAGE_TYPE = {v: k for k, v in MESSAGE_TYPE_MAP.items()}