"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MessageTypeId:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageTypeIdEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageTypeId.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MessageTypeIdUnspecified: _MessageTypeId.ValueType  # 0
    """Proto3 requires a zero value"""
    TypeHostCommandConfigurePeripheral: _MessageTypeId.ValueType  # 1
    """Host Commands
    Configure BLE peripheral device with name and 6-byte address
    """
    TypeHostCommandConfigureService: _MessageTypeId.ValueType  # 2
    """Create a new BLE service with specified u16 UUID"""
    TypeHostCommandConfigureCharacteristic: _MessageTypeId.ValueType  # 3
    """Create a BLE characteristic with properties"""
    TypeHostCommandConfigureCharacteristicRead: _MessageTypeId.ValueType  # 4
    """Configure characteristic for read operations with default value"""
    TypeHostCommandGetServiceInfo: _MessageTypeId.ValueType  # 5
    """Query information about a BLE service"""
    TypeHostCommandGetCharacteristicInfo: _MessageTypeId.ValueType  # 6
    """Query information about a BLE characteristic"""
    TypeHostCommandStartAdvertisement: _MessageTypeId.ValueType  # 7
    """Start BLE advertising with optional multi-connect support"""
    TypeHostCommandNotifyCharacteristicValue: _MessageTypeId.ValueType  # 8
    """Send notification/indication to connected BLE client"""
    TypeHostCommandConfigurePeripheralSecurity: _MessageTypeId.ValueType  # 9
    """Configure BLE security settings (pairing, bonding, passkey, etc.)"""
    TypeHostCommandConfigureProfile: _MessageTypeId.ValueType  # 10
    """Configure BLE profile with predefined services and characteristics"""
    TypeHostCommandStopAdvertisement: _MessageTypeId.ValueType  # 11
    """Stop BLE advertising"""
    TypeHostCommandQueryConnections: _MessageTypeId.ValueType  # 12
    """Query bluetooth connections"""
    TypePluginData: _MessageTypeId.ValueType  # 128
    """Plugin Responses
    Data forwarded from BLE client to BLE plugin
    """
    TypePluginConfigurationError: _MessageTypeId.ValueType  # 129
    """Configuration error response from plugin"""
    TypePluginServiceInfoResponse: _MessageTypeId.ValueType  # 130
    """Service information response with characteristic list"""
    TypePluginCharacteristicInfoResponse: _MessageTypeId.ValueType  # 131
    """Characteristic information response with properties"""
    TypePluginAuthenticationCompletedResponse: _MessageTypeId.ValueType  # 132
    """Authentication completed response from plugin"""
    TypePluginOnConnectResponse: _MessageTypeId.ValueType  # 133
    """Central device on connect response"""

class MessageTypeId(_MessageTypeId, metaclass=_MessageTypeIdEnumTypeWrapper):
    """Message Type IDs for protocol dispatch. Only supports 2^16 possible values.
    Note: Each message type is identified by its corresponding MessageTypeId enum value
    when serialized. The protocol uses the MessageTypeId in the message header to
    determine which specific message type to deserialize.
    @derive(strum::EnumIter)
    """

MessageTypeIdUnspecified: MessageTypeId.ValueType  # 0
"""Proto3 requires a zero value"""
TypeHostCommandConfigurePeripheral: MessageTypeId.ValueType  # 1
"""Host Commands
Configure BLE peripheral device with name and 6-byte address
"""
TypeHostCommandConfigureService: MessageTypeId.ValueType  # 2
"""Create a new BLE service with specified u16 UUID"""
TypeHostCommandConfigureCharacteristic: MessageTypeId.ValueType  # 3
"""Create a BLE characteristic with properties"""
TypeHostCommandConfigureCharacteristicRead: MessageTypeId.ValueType  # 4
"""Configure characteristic for read operations with default value"""
TypeHostCommandGetServiceInfo: MessageTypeId.ValueType  # 5
"""Query information about a BLE service"""
TypeHostCommandGetCharacteristicInfo: MessageTypeId.ValueType  # 6
"""Query information about a BLE characteristic"""
TypeHostCommandStartAdvertisement: MessageTypeId.ValueType  # 7
"""Start BLE advertising with optional multi-connect support"""
TypeHostCommandNotifyCharacteristicValue: MessageTypeId.ValueType  # 8
"""Send notification/indication to connected BLE client"""
TypeHostCommandConfigurePeripheralSecurity: MessageTypeId.ValueType  # 9
"""Configure BLE security settings (pairing, bonding, passkey, etc.)"""
TypeHostCommandConfigureProfile: MessageTypeId.ValueType  # 10
"""Configure BLE profile with predefined services and characteristics"""
TypeHostCommandStopAdvertisement: MessageTypeId.ValueType  # 11
"""Stop BLE advertising"""
TypeHostCommandQueryConnections: MessageTypeId.ValueType  # 12
"""Query bluetooth connections"""
TypePluginData: MessageTypeId.ValueType  # 128
"""Plugin Responses
Data forwarded from BLE client to BLE plugin
"""
TypePluginConfigurationError: MessageTypeId.ValueType  # 129
"""Configuration error response from plugin"""
TypePluginServiceInfoResponse: MessageTypeId.ValueType  # 130
"""Service information response with characteristic list"""
TypePluginCharacteristicInfoResponse: MessageTypeId.ValueType  # 131
"""Characteristic information response with properties"""
TypePluginAuthenticationCompletedResponse: MessageTypeId.ValueType  # 132
"""Authentication completed response from plugin"""
TypePluginOnConnectResponse: MessageTypeId.ValueType  # 133
"""Central device on connect response"""
global___MessageTypeId = MessageTypeId

class _BleProperties:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BlePropertiesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BleProperties.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BlePropertiesUnspecified: _BleProperties.ValueType  # 0
    """Proto3 requires a zero value"""
    Read: _BleProperties.ValueType  # 1
    """Read property"""
    WriteRsp: _BleProperties.ValueType  # 2
    """Write property"""
    WriteNoRsp: _BleProperties.ValueType  # 3
    """Write without response property"""
    Notify: _BleProperties.ValueType  # 4
    """Notify property"""
    Indicate: _BleProperties.ValueType  # 5
    """Indicate property"""

class BleProperties(_BleProperties, metaclass=_BlePropertiesEnumTypeWrapper):
    """Properties enumeration for BLE characteristics
    @derive(serde::Deserialize, serde::Serialize)
    """

BlePropertiesUnspecified: BleProperties.ValueType  # 0
"""Proto3 requires a zero value"""
Read: BleProperties.ValueType  # 1
"""Read property"""
WriteRsp: BleProperties.ValueType  # 2
"""Write property"""
WriteNoRsp: BleProperties.ValueType  # 3
"""Write without response property"""
Notify: BleProperties.ValueType  # 4
"""Notify property"""
Indicate: BleProperties.ValueType  # 5
"""Indicate property"""
global___BleProperties = BleProperties

class _BluetoothAddressType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BluetoothAddressTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BluetoothAddressType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BluetoothAddressTypeUnspecified: _BluetoothAddressType.ValueType  # 0
    """Proto3 requires a zero value"""
    Public: _BluetoothAddressType.ValueType  # 1
    """Public address"""
    Random: _BluetoothAddressType.ValueType  # 2
    """Random address"""
    PublicId: _BluetoothAddressType.ValueType  # 3
    """Public ID address"""
    RandomId: _BluetoothAddressType.ValueType  # 4
    """Random ID address"""

class BluetoothAddressType(_BluetoothAddressType, metaclass=_BluetoothAddressTypeEnumTypeWrapper):
    """Bluetooth Device address type
    @derive(serde::Deserialize, serde::Serialize)
    """

BluetoothAddressTypeUnspecified: BluetoothAddressType.ValueType  # 0
"""Proto3 requires a zero value"""
Public: BluetoothAddressType.ValueType  # 1
"""Public address"""
Random: BluetoothAddressType.ValueType  # 2
"""Random address"""
PublicId: BluetoothAddressType.ValueType  # 3
"""Public ID address"""
RandomId: BluetoothAddressType.ValueType  # 4
"""Random ID address"""
global___BluetoothAddressType = BluetoothAddressType

class _BleProfile:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BleProfileEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BleProfile.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BleProfileUnspecified: _BleProfile.ValueType  # 0
    """Proto3 requires a zero value"""
    Custom: _BleProfile.ValueType  # 1
    """Custom profile - user-defined services"""
    HeartRateMonitor: _BleProfile.ValueType  # 2
    """Heart Rate Monitor profile"""
    BatteryService: _BleProfile.ValueType  # 3
    """Battery Service profile"""
    DeviceInformation: _BleProfile.ValueType  # 4
    """Device Information Service profile"""

class BleProfile(_BleProfile, metaclass=_BleProfileEnumTypeWrapper):
    """Profile type enumeration for preconfigured BLE profiles
    @derive(serde::Deserialize, serde::Serialize)
    """

BleProfileUnspecified: BleProfile.ValueType  # 0
"""Proto3 requires a zero value"""
Custom: BleProfile.ValueType  # 1
"""Custom profile - user-defined services"""
HeartRateMonitor: BleProfile.ValueType  # 2
"""Heart Rate Monitor profile"""
BatteryService: BleProfile.ValueType  # 3
"""Battery Service profile"""
DeviceInformation: BleProfile.ValueType  # 4
"""Device Information Service profile"""
global___BleProfile = BleProfile

class _PluginDataSendType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PluginDataSendTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PluginDataSendType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PluginDataSendTypeUnspecified: _PluginDataSendType.ValueType  # 0
    """Proto3 requires a zero value"""
    NotifyType: _PluginDataSendType.ValueType  # 1
    """Notified from the central bluetooth device"""
    ReadType: _PluginDataSendType.ValueType  # 2
    """Read attempt from the central bluetooth device"""
    WriteType: _PluginDataSendType.ValueType  # 3
    """Written from the central bluetooth device"""

class PluginDataSendType(_PluginDataSendType, metaclass=_PluginDataSendTypeEnumTypeWrapper):
    """Plugin messages

    Represents the send type of the data. Was it due to a
    write event (central -> peripheral), notify event (peripheral -> central),
    or read attempt (central -> peripheral). Depending on which, a response
    might be expected or sent
    @derive(serde::Deserialize, serde::Serialize)
    """

PluginDataSendTypeUnspecified: PluginDataSendType.ValueType  # 0
"""Proto3 requires a zero value"""
NotifyType: PluginDataSendType.ValueType  # 1
"""Notified from the central bluetooth device"""
ReadType: PluginDataSendType.ValueType  # 2
"""Read attempt from the central bluetooth device"""
WriteType: PluginDataSendType.ValueType  # 3
"""Written from the central bluetooth device"""
global___PluginDataSendType = PluginDataSendType

class _PluginConfigurationErrorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PluginConfigurationErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PluginConfigurationErrorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PluginConfigurationErrorTypeUnspecified: _PluginConfigurationErrorType.ValueType  # 0
    """Proto3 requires a zero value"""
    PeripheralNameTooLong: _PluginConfigurationErrorType.ValueType  # 1
    """The peripheral name is too long"""
    InvalidPeripheralUuid: _PluginConfigurationErrorType.ValueType  # 2
    """The peripheral address is invalid"""
    InvalidServiceUuid: _PluginConfigurationErrorType.ValueType  # 3
    """The service UUID (u16) is invalid"""
    InvalidCharacteristicUuid: _PluginConfigurationErrorType.ValueType  # 4
    """The characteristic UUID (u16) is invalid"""
    AdvertisementWithoutPeripheralConfiguration: _PluginConfigurationErrorType.ValueType  # 5
    """Advertisement without proper peripheral configuration"""
    ServiceWithoutPeripheralConfiguration: _PluginConfigurationErrorType.ValueType  # 6
    """Service without proper peripheral configuration"""
    CharacteristicWithoutServiceConfiguration: _PluginConfigurationErrorType.ValueType  # 7
    """Characteristic without proper service configuration"""

class PluginConfigurationErrorType(_PluginConfigurationErrorType, metaclass=_PluginConfigurationErrorTypeEnumTypeWrapper):
    """Error type enumeration for plugin configuration errors
    @derive(serde::Deserialize, serde::Serialize)
    """

PluginConfigurationErrorTypeUnspecified: PluginConfigurationErrorType.ValueType  # 0
"""Proto3 requires a zero value"""
PeripheralNameTooLong: PluginConfigurationErrorType.ValueType  # 1
"""The peripheral name is too long"""
InvalidPeripheralUuid: PluginConfigurationErrorType.ValueType  # 2
"""The peripheral address is invalid"""
InvalidServiceUuid: PluginConfigurationErrorType.ValueType  # 3
"""The service UUID (u16) is invalid"""
InvalidCharacteristicUuid: PluginConfigurationErrorType.ValueType  # 4
"""The characteristic UUID (u16) is invalid"""
AdvertisementWithoutPeripheralConfiguration: PluginConfigurationErrorType.ValueType  # 5
"""Advertisement without proper peripheral configuration"""
ServiceWithoutPeripheralConfiguration: PluginConfigurationErrorType.ValueType  # 6
"""Service without proper peripheral configuration"""
CharacteristicWithoutServiceConfiguration: PluginConfigurationErrorType.ValueType  # 7
"""Characteristic without proper service configuration"""
global___PluginConfigurationErrorType = PluginConfigurationErrorType

@typing.final
class HostCommandConfigurePeripheral(google.protobuf.message.Message):
    """Host messages

    Host command. Configure peripheral
    Random Bluetooth addresses must follow specific MSB bit patterns:
    - Static Random: MSB bits = 11 (0xC0-0xFF), remaining 46 bits must have at least one 0 and one 1
    - Non-Resolvable Private: MSB bits = 00 (0x00-0x3F), remaining 46 bits must have at least one 0 and one 1
    Invalid pattern like 0xa1a1a1a1a1a1 has MSB bits = 10 (not allowed)

    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigurePeripheral))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Peripheral name"""
    addr: builtins.bytes
    """Peripheral addr
    6 bytes for Bluetooth address
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        addr: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addr", b"addr", "name", b"name"]) -> None: ...

global___HostCommandConfigurePeripheral = HostCommandConfigurePeripheral

@typing.final
class HostCommandConfigurePeripheralSecurity(google.protobuf.message.Message):
    """Host command. Configure peripheral security
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigurePeripheralSecurity))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSKEY_FIELD_NUMBER: builtins.int
    passkey: builtins.int
    """Passkey for pairing (6 digit numeric)"""
    def __init__(
        self,
        *,
        passkey: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["passkey", b"passkey"]) -> None: ...

global___HostCommandConfigurePeripheralSecurity = HostCommandConfigurePeripheralSecurity

@typing.final
class HostCommandConfigureService(google.protobuf.message.Message):
    """Host command. Configure service
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureService))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    uuid: builtins.int
    """Service UUID (u16)
    u16 in Rust, using uint32 in proto3
    """
    def __init__(
        self,
        *,
        uuid: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uuid", b"uuid"]) -> None: ...

global___HostCommandConfigureService = HostCommandConfigureService

@typing.final
class HostCommandConfigureCharacteristic(google.protobuf.message.Message):
    """Host command. Configure characteristic
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureCharacteristic))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    SERVICE_UUID_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    uuid: builtins.int
    """Characteristic UUID (u16)
    u16 in Rust
    """
    service_uuid: builtins.int
    """Service UUID (u16) this characteristic belongs to
    u16 in Rust
    """
    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___BleProperties.ValueType]:
        """Properties of the characteristic (read, write, notify, etc.)
        Max 4 properties per characteristic
        """

    def __init__(
        self,
        *,
        uuid: builtins.int = ...,
        service_uuid: builtins.int = ...,
        properties: collections.abc.Iterable[global___BleProperties.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["properties", b"properties", "service_uuid", b"service_uuid", "uuid", b"uuid"]) -> None: ...

global___HostCommandConfigureCharacteristic = HostCommandConfigureCharacteristic

@typing.final
class HostCommandConfigureCharacteristicRead(google.protobuf.message.Message):
    """Host command. Configure characteristic read
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureCharacteristicRead))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    SERVICE_UUID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    uuid: builtins.int
    """Characteristic UUID (u16)
    u16 in Rust
    """
    service_uuid: builtins.int
    """Service UUID (u16) this characteristic belongs to
    u16 in Rust
    """
    value: builtins.bytes
    """Read value
    Max MAX_NAME_SIZE bytes
    """
    def __init__(
        self,
        *,
        uuid: builtins.int = ...,
        service_uuid: builtins.int = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["service_uuid", b"service_uuid", "uuid", b"uuid", "value", b"value"]) -> None: ...

global___HostCommandConfigureCharacteristicRead = HostCommandConfigureCharacteristicRead

@typing.final
class HostCommandGetServiceInfo(google.protobuf.message.Message):
    """Host command. Get service info
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandGetServiceInfo))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    uuid: builtins.int
    """Service UUID (u16)
    u16 in Rust
    """
    def __init__(
        self,
        *,
        uuid: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uuid", b"uuid"]) -> None: ...

global___HostCommandGetServiceInfo = HostCommandGetServiceInfo

@typing.final
class HostCommandGetCharacteristicInfo(google.protobuf.message.Message):
    """Host command. Get characteristic info
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandGetCharacteristicInfo))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHARACTERISTIC_UUID_FIELD_NUMBER: builtins.int
    SERVICE_UUID_FIELD_NUMBER: builtins.int
    characteristic_uuid: builtins.int
    """Characteristic UUID (u16)
    u16 in Rust
    """
    service_uuid: builtins.int
    """Service UUID (u16) this characteristic belongs to
    u16 in Rust
    """
    def __init__(
        self,
        *,
        characteristic_uuid: builtins.int = ...,
        service_uuid: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["characteristic_uuid", b"characteristic_uuid", "service_uuid", b"service_uuid"]) -> None: ...

global___HostCommandGetCharacteristicInfo = HostCommandGetCharacteristicInfo

@typing.final
class HostCommandStartAdvertisement(google.protobuf.message.Message):
    """Host command. Start advertisement. TODO: Allow selecting which services you want to advertise
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandStartAdvertisement))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOW_MULTI_CONNECT_FIELD_NUMBER: builtins.int
    allow_multi_connect: builtins.bool
    """Allow multiple central connections"""
    def __init__(
        self,
        *,
        allow_multi_connect: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["allow_multi_connect", b"allow_multi_connect"]) -> None: ...

global___HostCommandStartAdvertisement = HostCommandStartAdvertisement

@typing.final
class HostCommandStopAdvertisement(google.protobuf.message.Message):
    """Host command. Stop all advertisement
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandStopAdvertisement))
    Empty message
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HostCommandStopAdvertisement = HostCommandStopAdvertisement

@typing.final
class HostCommandNotifyCharacteristicValue(google.protobuf.message.Message):
    """Host command. Notify characteristic value
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandNotifyCharacteristicValue))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    ADDRESS_TYPE_FIELD_NUMBER: builtins.int
    CHARACTERISTIC_UUID_FIELD_NUMBER: builtins.int
    SERVICE_UUID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    address: builtins.bytes
    """Device Address
    6 bytes
    """
    address_type: global___BluetoothAddressType.ValueType
    """Address type"""
    characteristic_uuid: builtins.int
    """Characteristic UUID (u16)
    u16 in Rust
    """
    service_uuid: builtins.int
    """Service UUID (u16) this characteristic belongs to
    u16 in Rust
    """
    value: builtins.bytes
    """Value to notify
    Max MAX_NAME_SIZE bytes
    """
    def __init__(
        self,
        *,
        address: builtins.bytes = ...,
        address_type: global___BluetoothAddressType.ValueType = ...,
        characteristic_uuid: builtins.int = ...,
        service_uuid: builtins.int = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "address_type", b"address_type", "characteristic_uuid", b"characteristic_uuid", "service_uuid", b"service_uuid", "value", b"value"]) -> None: ...

global___HostCommandNotifyCharacteristicValue = HostCommandNotifyCharacteristicValue

@typing.final
class HostCommandQueryConnections(google.protobuf.message.Message):
    """Host command. Query connections
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandQueryConnections))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HostCommandQueryConnections = HostCommandQueryConnections

@typing.final
class PluginOnConnectResponse(google.protobuf.message.Message):
    """Plugin connection response.
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginOnConnectResponse))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    ADDRESS_TYPE_FIELD_NUMBER: builtins.int
    address: builtins.bytes
    """Device Address
    6 bytes
    """
    address_type: global___BluetoothAddressType.ValueType
    """Address type"""
    def __init__(
        self,
        *,
        address: builtins.bytes = ...,
        address_type: global___BluetoothAddressType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "address_type", b"address_type"]) -> None: ...

global___PluginOnConnectResponse = PluginOnConnectResponse

@typing.final
class HostCommandConfigureProfile(google.protobuf.message.Message):
    """Host command. Configure BLE profile
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureProfile))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILE_FIELD_NUMBER: builtins.int
    profile: global___BleProfile.ValueType
    """Profile type to configure"""
    def __init__(
        self,
        *,
        profile: global___BleProfile.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profile", b"profile"]) -> None: ...

global___HostCommandConfigureProfile = HostCommandConfigureProfile

@typing.final
class PluginData(google.protobuf.message.Message):
    """Plugin data
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginData))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SRC_ADDR_FIELD_NUMBER: builtins.int
    SRC_ADDR_TYPE_FIELD_NUMBER: builtins.int
    SEND_TYPE_FIELD_NUMBER: builtins.int
    CHARACTERISTIC_UUID_FIELD_NUMBER: builtins.int
    SERVICE_UUID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    src_addr: builtins.bytes
    """Source peripheral addr that this data is originating from
    6 bytes
    """
    src_addr_type: global___BluetoothAddressType.ValueType
    """Address type of the source peripheral"""
    send_type: global___PluginDataSendType.ValueType
    """Send type of the data"""
    characteristic_uuid: builtins.int
    """Characteristic UUID (u16)
    u16 in Rust
    """
    service_uuid: builtins.int
    """Service UUID (u16) this characteristic belongs to
    u16 in Rust
    """
    data: builtins.bytes
    """Actual command type"""
    def __init__(
        self,
        *,
        src_addr: builtins.bytes = ...,
        src_addr_type: global___BluetoothAddressType.ValueType = ...,
        send_type: global___PluginDataSendType.ValueType = ...,
        characteristic_uuid: builtins.int = ...,
        service_uuid: builtins.int = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["characteristic_uuid", b"characteristic_uuid", "data", b"data", "send_type", b"send_type", "service_uuid", b"service_uuid", "src_addr", b"src_addr", "src_addr_type", b"src_addr_type"]) -> None: ...

global___PluginData = PluginData

@typing.final
class PluginConfigurationError(google.protobuf.message.Message):
    """Plugin configuration error message
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginConfigurationError))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_TYPE_FIELD_NUMBER: builtins.int
    error_type: global___PluginConfigurationErrorType.ValueType
    """The type of configuration error"""
    def __init__(
        self,
        *,
        error_type: global___PluginConfigurationErrorType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_type", b"error_type"]) -> None: ...

global___PluginConfigurationError = PluginConfigurationError

@typing.final
class PluginServiceInfoResponse(google.protobuf.message.Message):
    """Service information response
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginServiceInfoResponse))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_UUID_FIELD_NUMBER: builtins.int
    CHARACTERISTIC_UUIDS_FIELD_NUMBER: builtins.int
    EXISTS_FIELD_NUMBER: builtins.int
    service_uuid: builtins.int
    """Service UUID (u16)
    u16 in Rust
    """
    exists: builtins.bool
    """Whether the service exists"""
    @property
    def characteristic_uuids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """List of characteristic UUIDs (u16) in this service
        u16 array, max 16 characteristics per service
        """

    def __init__(
        self,
        *,
        service_uuid: builtins.int = ...,
        characteristic_uuids: collections.abc.Iterable[builtins.int] | None = ...,
        exists: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["characteristic_uuids", b"characteristic_uuids", "exists", b"exists", "service_uuid", b"service_uuid"]) -> None: ...

global___PluginServiceInfoResponse = PluginServiceInfoResponse

@typing.final
class PluginCharacteristicInfoResponse(google.protobuf.message.Message):
    """Characteristic information response
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginCharacteristicInfoResponse))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHARACTERISTIC_UUID_FIELD_NUMBER: builtins.int
    SERVICE_UUID_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    EXISTS_FIELD_NUMBER: builtins.int
    characteristic_uuid: builtins.int
    """Characteristic UUID (u16)
    u16 in Rust
    """
    service_uuid: builtins.int
    """Service UUID (u16) this characteristic belongs to
    u16 in Rust
    """
    exists: builtins.bool
    """Whether the characteristic exists"""
    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___BleProperties.ValueType]:
        """Properties of the characteristic (read, write, notify, etc.)
        Max 4 properties
        """

    def __init__(
        self,
        *,
        characteristic_uuid: builtins.int = ...,
        service_uuid: builtins.int = ...,
        properties: collections.abc.Iterable[global___BleProperties.ValueType] | None = ...,
        exists: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["characteristic_uuid", b"characteristic_uuid", "exists", b"exists", "properties", b"properties", "service_uuid", b"service_uuid"]) -> None: ...

global___PluginCharacteristicInfoResponse = PluginCharacteristicInfoResponse

@typing.final
class PluginAuthenticationCompletedResponse(google.protobuf.message.Message):
    """Plugin authentication completed response
    @derive(serde::Deserialize, serde::Serialize)
    @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginAuthenticationCompletedResponse))
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    ADDRESS_TYPE_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    address: builtins.bytes
    """Address of the device that was authenticated
    6 bytes
    """
    address_type: global___BluetoothAddressType.ValueType
    """Address type"""
    success: builtins.bool
    """Whether the authentication was successful"""
    def __init__(
        self,
        *,
        address: builtins.bytes = ...,
        address_type: global___BluetoothAddressType.ValueType = ...,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "address_type", b"address_type", "success", b"success"]) -> None: ...

global___PluginAuthenticationCompletedResponse = PluginAuthenticationCompletedResponse
