// This file is @generated by prost-build.
use crate::{IO, IOBase, HostIO, PluginIO, MessageType};


/// Host command. Configure peripheral
/// Random Bluetooth addresses must follow specific MSB bit patterns:
/// - Static Random: MSB bits = 11 (0xC0-0xFF), remaining 46 bits must have at least one 0 and one 1
/// - Non-Resolvable Private: MSB bits = 00 (0x00-0x3F), remaining 46 bits must have at least one 0 and one 1
/// Invalid pattern like 0xa1a1a1a1a1a1 has MSB bits = 10 (not allowed)
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigurePeripheral))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigurePeripheral)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandConfigurePeripheral {
    /// Peripheral name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Peripheral addr
    ///
    /// 6 bytes for Bluetooth address
    #[prost(bytes = "vec", tag = "2")]
    pub addr: ::prost::alloc::vec::Vec<u8>,
}
/// Host command. Configure peripheral security
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigurePeripheralSecurity))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigurePeripheralSecurity)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandConfigurePeripheralSecurity {
    /// Passkey for pairing (6 digit numeric)
    #[prost(uint32, tag = "1")]
    pub passkey: u32,
}
/// Host command. Configure service
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureService))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureService)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandConfigureService {
    /// Service UUID (u16)
    ///
    /// u16 in Rust, using uint32 in proto3
    #[prost(uint32, tag = "1")]
    pub uuid: u32,
}
/// Host command. Configure characteristic
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureCharacteristic))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureCharacteristic)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandConfigureCharacteristic {
    /// Characteristic UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "1")]
    pub uuid: u32,
    /// Service UUID (u16) this characteristic belongs to
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "2")]
    pub service_uuid: u32,
    /// Properties of the characteristic (read, write, notify, etc.)
    ///
    /// Max 4 properties per characteristic
    #[prost(enumeration = "BleProperties", repeated, tag = "3")]
    pub properties: ::prost::alloc::vec::Vec<i32>,
}
/// Host command. Configure characteristic read
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureCharacteristicRead))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureCharacteristicRead)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandConfigureCharacteristicRead {
    /// Characteristic UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "1")]
    pub uuid: u32,
    /// Service UUID (u16) this characteristic belongs to
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "2")]
    pub service_uuid: u32,
    /// Read value
    ///
    /// Max MAX_NAME_SIZE bytes
    #[prost(bytes = "vec", tag = "3")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// Host command. Get service info
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandGetServiceInfo))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandGetServiceInfo)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandGetServiceInfo {
    /// Service UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "1")]
    pub uuid: u32,
}
/// Host command. Get characteristic info
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandGetCharacteristicInfo))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandGetCharacteristicInfo)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandGetCharacteristicInfo {
    /// Characteristic UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "1")]
    pub characteristic_uuid: u32,
    /// Service UUID (u16) this characteristic belongs to
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "2")]
    pub service_uuid: u32,
}
/// Host command. Start advertisement. TODO: Allow selecting which services you want to advertise
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandStartAdvertisement))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandStartAdvertisement)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandStartAdvertisement {
    /// Allow multiple central connections
    #[prost(bool, tag = "1")]
    pub allow_multi_connect: bool,
}
/// Host command. Stop all advertisement
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandStopAdvertisement))
///
/// Empty message
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandStopAdvertisement)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandStopAdvertisement {}
/// Host command. Notify characteristic value
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandNotifyCharacteristicValue))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandNotifyCharacteristicValue)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandNotifyCharacteristicValue {
    /// Device Address
    ///
    /// 6 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// Address type
    #[prost(enumeration = "BluetoothAddressType", tag = "2")]
    pub address_type: i32,
    /// Characteristic UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "3")]
    pub characteristic_uuid: u32,
    /// Service UUID (u16) this characteristic belongs to
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "4")]
    pub service_uuid: u32,
    /// Value to notify
    ///
    /// Max MAX_NAME_SIZE bytes
    #[prost(bytes = "vec", tag = "5")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// Host command. Configure BLE profile
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureProfile))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::HostIO(MessageTypeId::TypeHostCommandConfigureProfile)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCommandConfigureProfile {
    /// Profile type to configure
    #[prost(enumeration = "BleProfile", tag = "1")]
    pub profile: i32,
}
/// Plugin data
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginData))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::PluginIO(MessageTypeId::TypePluginData)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginData {
    /// Source peripheral addr that this data is originating from
    ///
    /// 6 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub src_addr: ::prost::alloc::vec::Vec<u8>,
    /// Address type of the source peripheral
    #[prost(enumeration = "BluetoothAddressType", tag = "2")]
    pub src_addr_type: i32,
    /// Send type of the data
    #[prost(enumeration = "PluginDataSendType", tag = "3")]
    pub send_type: i32,
    /// Characteristic UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "4")]
    pub characteristic_uuid: u32,
    /// Service UUID (u16) this characteristic belongs to
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "5")]
    pub service_uuid: u32,
    /// Actual command type
    #[prost(bytes = "vec", tag = "6")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Plugin configuration error message
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginConfigurationError))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::PluginIO(MessageTypeId::TypePluginConfigurationError)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginConfigurationError {
    /// The type of configuration error
    #[prost(enumeration = "PluginConfigurationErrorType", tag = "1")]
    pub error_type: i32,
}
/// Service information response
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginServiceInfoResponse))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::PluginIO(MessageTypeId::TypePluginServiceInfoResponse)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginServiceInfoResponse {
    /// Service UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "1")]
    pub service_uuid: u32,
    /// List of characteristic UUIDs (u16) in this service
    ///
    /// u16 array, max 16 characteristics per service
    #[prost(uint32, repeated, tag = "2")]
    pub characteristic_uuids: ::prost::alloc::vec::Vec<u32>,
    /// Whether the service exists
    #[prost(bool, tag = "3")]
    pub exists: bool,
}
/// Characteristic information response
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginCharacteristicInfoResponse))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::PluginIO(MessageTypeId::TypePluginCharacteristicInfoResponse)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginCharacteristicInfoResponse {
    /// Characteristic UUID (u16)
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "1")]
    pub characteristic_uuid: u32,
    /// Service UUID (u16) this characteristic belongs to
    ///
    /// u16 in Rust
    #[prost(uint32, tag = "2")]
    pub service_uuid: u32,
    /// Properties of the characteristic (read, write, notify, etc.)
    ///
    /// Max 4 properties
    #[prost(enumeration = "BleProperties", repeated, tag = "3")]
    pub properties: ::prost::alloc::vec::Vec<i32>,
    /// Whether the characteristic exists
    #[prost(bool, tag = "4")]
    pub exists: bool,
}
/// Plugin authentication completed response
/// @derive(serde::Deserialize, serde::Serialize)
/// @rust_macro(protocol_io::PluginIO(MessageTypeId::TypePluginAuthenticationCompletedResponse))
#[derive(serde::Deserialize, serde::Serialize)]
#[protocol_io::PluginIO(MessageTypeId::TypePluginAuthenticationCompletedResponse)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginAuthenticationCompletedResponse {
    /// Address of the device that was authenticated
    ///
    /// 6 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// Address type
    #[prost(enumeration = "BluetoothAddressType", tag = "2")]
    pub address_type: i32,
    /// Whether the authentication was successful
    #[prost(bool, tag = "3")]
    pub success: bool,
}
/// Message Type IDs for protocol dispatch
/// Note: Each message type is identified by its corresponding MessageTypeId enum value
/// when serialized. The protocol uses the MessageTypeId in the message header to
/// determine which specific message type to deserialize.
/// @derive(strum::EnumIter)
#[derive(strum::EnumIter)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageTypeId {
    /// Proto3 requires a zero value
    Unspecified = 0,
    /// Host Commands (0x01-0x0F)
    /// Configure BLE peripheral device with name and 6-byte address
    TypeHostCommandConfigurePeripheral = 1,
    /// Create a new BLE service with specified u16 UUID
    TypeHostCommandConfigureService = 2,
    /// Create a BLE characteristic with properties
    TypeHostCommandConfigureCharacteristic = 3,
    /// Configure characteristic for read operations with default value
    TypeHostCommandConfigureCharacteristicRead = 4,
    /// Query information about a BLE service
    TypeHostCommandGetServiceInfo = 5,
    /// Query information about a BLE characteristic
    TypeHostCommandGetCharacteristicInfo = 6,
    /// Start BLE advertising with optional multi-connect support
    TypeHostCommandStartAdvertisement = 7,
    /// Send notification/indication to connected BLE client
    TypeHostCommandNotifyCharacteristicValue = 8,
    /// Configure BLE security settings (pairing, bonding, passkey, etc.)
    TypeHostCommandConfigurePeripheralSecurity = 9,
    /// Configure BLE profile with predefined services and characteristics
    TypeHostCommandConfigureProfile = 10,
    /// Stop BLE advertising
    TypeHostCommandStopAdvertisement = 11,
    /// Plugin Responses (0x80+)
    /// Data forwarded from BLE client to BLE plugin
    TypePluginData = 128,
    /// Configuration error response from plugin
    TypePluginConfigurationError = 129,
    /// Service information response with characteristic list
    TypePluginServiceInfoResponse = 130,
    /// Characteristic information response with properties
    TypePluginCharacteristicInfoResponse = 131,
    /// Authentication completed response from plugin
    TypePluginAuthenticationCompletedResponse = 132,
}
impl MessageTypeId {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MessageTypeIdUnspecified",
            Self::TypeHostCommandConfigurePeripheral => {
                "TypeHostCommandConfigurePeripheral"
            }
            Self::TypeHostCommandConfigureService => "TypeHostCommandConfigureService",
            Self::TypeHostCommandConfigureCharacteristic => {
                "TypeHostCommandConfigureCharacteristic"
            }
            Self::TypeHostCommandConfigureCharacteristicRead => {
                "TypeHostCommandConfigureCharacteristicRead"
            }
            Self::TypeHostCommandGetServiceInfo => "TypeHostCommandGetServiceInfo",
            Self::TypeHostCommandGetCharacteristicInfo => {
                "TypeHostCommandGetCharacteristicInfo"
            }
            Self::TypeHostCommandStartAdvertisement => {
                "TypeHostCommandStartAdvertisement"
            }
            Self::TypeHostCommandNotifyCharacteristicValue => {
                "TypeHostCommandNotifyCharacteristicValue"
            }
            Self::TypeHostCommandConfigurePeripheralSecurity => {
                "TypeHostCommandConfigurePeripheralSecurity"
            }
            Self::TypeHostCommandConfigureProfile => "TypeHostCommandConfigureProfile",
            Self::TypeHostCommandStopAdvertisement => "TypeHostCommandStopAdvertisement",
            Self::TypePluginData => "TypePluginData",
            Self::TypePluginConfigurationError => "TypePluginConfigurationError",
            Self::TypePluginServiceInfoResponse => "TypePluginServiceInfoResponse",
            Self::TypePluginCharacteristicInfoResponse => {
                "TypePluginCharacteristicInfoResponse"
            }
            Self::TypePluginAuthenticationCompletedResponse => {
                "TypePluginAuthenticationCompletedResponse"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MessageTypeIdUnspecified" => Some(Self::Unspecified),
            "TypeHostCommandConfigurePeripheral" => {
                Some(Self::TypeHostCommandConfigurePeripheral)
            }
            "TypeHostCommandConfigureService" => {
                Some(Self::TypeHostCommandConfigureService)
            }
            "TypeHostCommandConfigureCharacteristic" => {
                Some(Self::TypeHostCommandConfigureCharacteristic)
            }
            "TypeHostCommandConfigureCharacteristicRead" => {
                Some(Self::TypeHostCommandConfigureCharacteristicRead)
            }
            "TypeHostCommandGetServiceInfo" => Some(Self::TypeHostCommandGetServiceInfo),
            "TypeHostCommandGetCharacteristicInfo" => {
                Some(Self::TypeHostCommandGetCharacteristicInfo)
            }
            "TypeHostCommandStartAdvertisement" => {
                Some(Self::TypeHostCommandStartAdvertisement)
            }
            "TypeHostCommandNotifyCharacteristicValue" => {
                Some(Self::TypeHostCommandNotifyCharacteristicValue)
            }
            "TypeHostCommandConfigurePeripheralSecurity" => {
                Some(Self::TypeHostCommandConfigurePeripheralSecurity)
            }
            "TypeHostCommandConfigureProfile" => {
                Some(Self::TypeHostCommandConfigureProfile)
            }
            "TypeHostCommandStopAdvertisement" => {
                Some(Self::TypeHostCommandStopAdvertisement)
            }
            "TypePluginData" => Some(Self::TypePluginData),
            "TypePluginConfigurationError" => Some(Self::TypePluginConfigurationError),
            "TypePluginServiceInfoResponse" => Some(Self::TypePluginServiceInfoResponse),
            "TypePluginCharacteristicInfoResponse" => {
                Some(Self::TypePluginCharacteristicInfoResponse)
            }
            "TypePluginAuthenticationCompletedResponse" => {
                Some(Self::TypePluginAuthenticationCompletedResponse)
            }
            _ => None,
        }
    }
}
/// Properties enumeration for BLE characteristics
/// @derive(serde::Deserialize, serde::Serialize)
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BleProperties {
    /// Proto3 requires a zero value
    Unspecified = 0,
    /// Read property
    Read = 1,
    /// Write property
    Write = 2,
    /// Write without response property
    WriteNoRsp = 3,
    /// Notify property
    Notify = 4,
    /// Indicate property
    Indicate = 5,
}
impl BleProperties {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BlePropertiesUnspecified",
            Self::Read => "Read",
            Self::Write => "Write",
            Self::WriteNoRsp => "WriteNoRsp",
            Self::Notify => "Notify",
            Self::Indicate => "Indicate",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BlePropertiesUnspecified" => Some(Self::Unspecified),
            "Read" => Some(Self::Read),
            "Write" => Some(Self::Write),
            "WriteNoRsp" => Some(Self::WriteNoRsp),
            "Notify" => Some(Self::Notify),
            "Indicate" => Some(Self::Indicate),
            _ => None,
        }
    }
}
/// Bluetooth Device address type
/// @derive(serde::Deserialize, serde::Serialize)
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BluetoothAddressType {
    /// Proto3 requires a zero value
    Unspecified = 0,
    /// Public address
    Public = 1,
    /// Random address
    Random = 2,
    /// Public ID address
    PublicId = 3,
    /// Random ID address
    RandomId = 4,
}
impl BluetoothAddressType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BluetoothAddressTypeUnspecified",
            Self::Public => "Public",
            Self::Random => "Random",
            Self::PublicId => "PublicId",
            Self::RandomId => "RandomId",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BluetoothAddressTypeUnspecified" => Some(Self::Unspecified),
            "Public" => Some(Self::Public),
            "Random" => Some(Self::Random),
            "PublicId" => Some(Self::PublicId),
            "RandomId" => Some(Self::RandomId),
            _ => None,
        }
    }
}
/// Profile type enumeration for preconfigured BLE profiles
/// @derive(serde::Deserialize, serde::Serialize)
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BleProfile {
    /// Proto3 requires a zero value
    Unspecified = 0,
    /// Custom profile - user-defined services
    Custom = 1,
    /// Heart Rate Monitor profile
    HeartRateMonitor = 2,
    /// Battery Service profile
    BatteryService = 3,
    /// Device Information Service profile
    DeviceInformation = 4,
}
impl BleProfile {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BleProfileUnspecified",
            Self::Custom => "Custom",
            Self::HeartRateMonitor => "HeartRateMonitor",
            Self::BatteryService => "BatteryService",
            Self::DeviceInformation => "DeviceInformation",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BleProfileUnspecified" => Some(Self::Unspecified),
            "Custom" => Some(Self::Custom),
            "HeartRateMonitor" => Some(Self::HeartRateMonitor),
            "BatteryService" => Some(Self::BatteryService),
            "DeviceInformation" => Some(Self::DeviceInformation),
            _ => None,
        }
    }
}
/// Represents the send type of the data. Was it due to a
/// write event (central -> peripheral), notify event (peripheral -> central),
/// or read attempt (central -> peripheral). Depending on which, a response
/// might be expected or sent
/// @derive(serde::Deserialize, serde::Serialize)
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PluginDataSendType {
    /// Proto3 requires a zero value
    Unspecified = 0,
    /// Notified from the central bluetooth device
    NotifyType = 1,
    /// Read attempt from the central bluetooth device
    ReadType = 2,
    /// Written from the central bluetooth device
    WriteType = 3,
}
impl PluginDataSendType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PluginDataSendTypeUnspecified",
            Self::NotifyType => "NotifyType",
            Self::ReadType => "ReadType",
            Self::WriteType => "WriteType",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PluginDataSendTypeUnspecified" => Some(Self::Unspecified),
            "NotifyType" => Some(Self::NotifyType),
            "ReadType" => Some(Self::ReadType),
            "WriteType" => Some(Self::WriteType),
            _ => None,
        }
    }
}
/// Error type enumeration for plugin configuration errors
/// @derive(serde::Deserialize, serde::Serialize)
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PluginConfigurationErrorType {
    /// Proto3 requires a zero value
    Unspecified = 0,
    /// The peripheral name is too long
    PeripheralNameTooLong = 1,
    /// The peripheral address is invalid
    InvalidPeripheralUuid = 2,
    /// The service UUID (u16) is invalid
    InvalidServiceUuid = 3,
    /// The characteristic UUID (u16) is invalid
    InvalidCharacteristicUuid = 4,
    /// Advertisement without proper peripheral configuration
    AdvertisementWithoutPeripheralConfiguration = 5,
    /// Service without proper peripheral configuration
    ServiceWithoutPeripheralConfiguration = 6,
    /// Characteristic without proper service configuration
    CharacteristicWithoutServiceConfiguration = 7,
}
impl PluginConfigurationErrorType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PluginConfigurationErrorTypeUnspecified",
            Self::PeripheralNameTooLong => "PeripheralNameTooLong",
            Self::InvalidPeripheralUuid => "InvalidPeripheralUuid",
            Self::InvalidServiceUuid => "InvalidServiceUuid",
            Self::InvalidCharacteristicUuid => "InvalidCharacteristicUuid",
            Self::AdvertisementWithoutPeripheralConfiguration => {
                "AdvertisementWithoutPeripheralConfiguration"
            }
            Self::ServiceWithoutPeripheralConfiguration => {
                "ServiceWithoutPeripheralConfiguration"
            }
            Self::CharacteristicWithoutServiceConfiguration => {
                "CharacteristicWithoutServiceConfiguration"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PluginConfigurationErrorTypeUnspecified" => Some(Self::Unspecified),
            "PeripheralNameTooLong" => Some(Self::PeripheralNameTooLong),
            "InvalidPeripheralUuid" => Some(Self::InvalidPeripheralUuid),
            "InvalidServiceUuid" => Some(Self::InvalidServiceUuid),
            "InvalidCharacteristicUuid" => Some(Self::InvalidCharacteristicUuid),
            "AdvertisementWithoutPeripheralConfiguration" => {
                Some(Self::AdvertisementWithoutPeripheralConfiguration)
            }
            "ServiceWithoutPeripheralConfiguration" => {
                Some(Self::ServiceWithoutPeripheralConfiguration)
            }
            "CharacteristicWithoutServiceConfiguration" => {
                Some(Self::CharacteristicWithoutServiceConfiguration)
            }
            _ => None,
        }
    }
}
