[package]
name = "plugin_state_machine_std"
version = "0.1.0"
edition = "2024"

[dependencies]
# Custom
protocol = { path = "../protocol" }
# Crates
esp32-nimble = { version = "0.11.0", default-features = false, features = [
    "no_std",
] }
log = "0.4"
heapless = "0.8.0"
esp-idf-svc = { version = "0.51", default-features = false }
uuid = { version = "1.17.0", default-features = false }
